//! Canonical predicates exercised by the differential harness.
//!
//! Each predicate is defined twice:
//!
//! 1. Once via `#[pyana_caveat]` so the DSL emits the full backend zoo
//!    (`_check`, `_air_constraints`, `_datalog`, `_kimchi`, `_midnight_zkir`,
//!    `_sp1_guest`, plus the compile-time `{Name}P3Air` struct).
//! 2. Once via a [`PredicateSpec`] entry that captures (a) the predicate's
//!    canonical name, (b) its semantic shape encoded as
//!    [`PredicateBody`] so the kimchi/AIR/plonky3 simulators can render the
//!    same predicate into their own substrate, and (c) the curated input
//!    battery to drive through every backend.
//!
//! Why the dual definition? The Rust evaluator generated by `gen_rust` is the
//! ground truth — but the other backends emit topology (Kimchi gates, AIR
//! columns, ZKIR JSON) without an in-process verifier function. To
//! cross-check those backends we re-derive the same predicate semantically
//! using the IR-aligned helpers in `pyana_dsl_runtime::diff_witness` and the
//! shape-aware simulators in this crate. The dual definition is the price of
//! not requiring the SP1 toolchain or Midnight's proof server to run a test.

use std::collections::HashSet;

use pyana_dsl::pyana_caveat;
use pyana_dsl_runtime::ConstraintError;

// ============================================================================
// DSL caveat definitions (the canonical source of truth for each predicate).
// ============================================================================
//
// Pre-edition note: pyana_caveat parses the function body and emits the
// matching backends. The bodies below MUST stay simple enough that all
// backends accept them; if you add a body with no IR support in one backend,
// that backend will be reported as Skip(reason) downstream.

#[pyana_caveat]
fn diff_not_after(token_expiry: u64, current_time: u64) {
    require!(current_time <= token_expiry);
}

#[pyana_caveat]
fn diff_minimum_balance(balance: u64, threshold: u64) {
    require!(balance >= threshold);
}

#[pyana_caveat]
fn diff_exact_equal_u64(expected: u64, actual: u64) {
    require!(expected == actual);
}

#[pyana_caveat]
fn diff_distinct_u64(a: u64, b: u64) {
    require!(a != b);
}

#[pyana_caveat]
fn diff_exact_equal_bytes(expected: [u8; 32], actual: [u8; 32]) {
    require!(expected == actual);
}

#[pyana_caveat]
fn diff_distinct_bytes(a: [u8; 32], b: [u8; 32]) {
    require!(a != b);
}

#[pyana_caveat]
fn diff_conjunction(balance: u64, threshold: u64, sender: u64, receiver: u64) {
    require!(balance >= threshold);
    require!(sender != receiver);
}

#[pyana_caveat]
fn diff_window(low: u64, mid: u64, high: u64) {
    require!(low <= mid);
    require!(mid <= high);
}

#[pyana_caveat]
fn diff_set_member(allowed: &std::collections::HashSet<u64>, candidate: u64) {
    require!(allowed.contains(candidate));
}

#[pyana_caveat]
fn diff_set_member_and_floor(allowed: &std::collections::HashSet<u64>, candidate: u64, floor: u64) {
    require!(allowed.contains(candidate));
    require!(candidate >= floor);
}

#[pyana_caveat]
fn diff_triple_equal(a: u64, b: u64, c: u64) {
    require!(a == b);
    require!(b == c);
}

// ============================================================================
// Semantic shape catalog
// ============================================================================

/// A single requirement comparable by all backends. Kept separate from
/// `pyana_dsl::ir` (which is internal to the proc-macro crate) so this crate
/// can stand alone.
#[derive(Clone)]
pub enum Requirement {
    LessEqualU64(u64, u64),
    GreaterEqualU64(u64, u64),
    EqualU64(u64, u64),
    NotEqualU64(u64, u64),
    EqualBytes32([u8; 32], [u8; 32]),
    NotEqualBytes32([u8; 32], [u8; 32]),
    Membership { set: HashSet<u64>, element: u64 },
}

impl std::fmt::Debug for Requirement {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::LessEqualU64(l, r) => write!(f, "LessEqualU64({l}, {r})"),
            Self::GreaterEqualU64(l, r) => write!(f, "GreaterEqualU64({l}, {r})"),
            Self::EqualU64(l, r) => write!(f, "EqualU64({l}, {r})"),
            Self::NotEqualU64(l, r) => write!(f, "NotEqualU64({l}, {r})"),
            Self::EqualBytes32(_, _) => write!(f, "EqualBytes32(.., ..)"),
            Self::NotEqualBytes32(_, _) => write!(f, "NotEqualBytes32(.., ..)"),
            Self::Membership { set, element } => {
                write!(f, "Membership(|set|={}, element={element})", set.len())
            }
        }
    }
}

impl Requirement {
    /// The IR-level truth of this requirement.
    pub fn holds(&self) -> bool {
        match self {
            Self::LessEqualU64(l, r) => l <= r,
            Self::GreaterEqualU64(l, r) => l >= r,
            Self::EqualU64(l, r) => l == r,
            Self::NotEqualU64(l, r) => l != r,
            Self::EqualBytes32(l, r) => l == r,
            Self::NotEqualBytes32(l, r) => l != r,
            Self::Membership { set, element } => set.contains(element),
        }
    }
}

/// The body of a predicate as a conjunction of requirements (all backends
/// fail-fast on the first unsatisfied requirement, matching how the
/// generated `{name}_check` is emitted).
#[derive(Debug, Clone)]
pub struct PredicateBody {
    pub requirements: Vec<Requirement>,
}

impl PredicateBody {
    pub fn holds(&self) -> bool {
        self.requirements.iter().all(|r| r.holds())
    }
}

/// One full case: a body bound to concrete inputs, plus a label for
/// disagreement reports.
pub struct PredicateCase {
    pub label: String,
    pub body: PredicateBody,
    /// Direct invocation of the `gen_rust` evaluator for this predicate's
    /// inputs. Returning `Ok(())` means "accept", `Err(_)` means "reject".
    pub rust_eval: Box<dyn Fn() -> Result<(), ConstraintError>>,
    /// Concrete parameter values keyed by parameter name. The Datalog
    /// evaluator binds variables from this map; the lint passes consult
    /// the keys to confirm the emitted artefacts reference every parameter.
    pub inputs: CaseInputs,
}

/// Concrete inputs to a predicate, keyed by parameter name. The names
/// here MUST match the parameter names declared on the `#[pyana_caveat]`
/// function that produced the emitted artefacts.
#[derive(Default, Clone)]
pub struct CaseInputs {
    pub u64s: Vec<(&'static str, u64)>,
    pub bytes: Vec<(&'static str, [u8; 32])>,
    pub sets: Vec<(&'static str, HashSet<u64>)>,
}

impl CaseInputs {
    pub fn new() -> Self {
        Self::default()
    }
    pub fn u64(mut self, name: &'static str, v: u64) -> Self {
        self.u64s.push((name, v));
        self
    }
    pub fn bytes(mut self, name: &'static str, v: [u8; 32]) -> Self {
        self.bytes.push((name, v));
        self
    }
    pub fn set(mut self, name: &'static str, v: HashSet<u64>) -> Self {
        self.sets.push((name, v));
        self
    }
}

/// One predicate definition: its canonical name, the IR-shape catalog of
/// its body (which all simulators consult), and the input battery.
pub struct PredicateSpec {
    pub name: &'static str,
    /// Lazy thunk producing the case battery. Owns its own `HashSet`s.
    pub cases: fn() -> Vec<PredicateCase>,
}

// ============================================================================
// Case batteries: each one binds the `#[pyana_caveat]`-generated `_check`
// against the same data fed to the IR-shape simulators downstream.
// ============================================================================

fn cases_not_after() -> Vec<PredicateCase> {
    // pyana-caveat signature: diff_not_after(token_expiry, current_time);
    // requirement: current_time <= token_expiry.
    let mk = |expiry: u64, now: u64| {
        let inputs = CaseInputs::new()
            .u64("token_expiry", expiry)
            .u64("current_time", now);
        let req = Requirement::LessEqualU64(now, expiry);
        (req, inputs)
    };
    let mut out = Vec::new();
    let scenarios = [
        ("expiry-in-future", 100u64, 50u64),
        ("expiry-equal", 100, 100),
        ("expiry-past", 100, 101),
        ("boundary-zero", 0, 0),
        ("boundary-max", u64::MAX, u64::MAX),
        ("near-overflow-reject", u64::MAX - 1, u64::MAX),
    ];
    for (label, expiry, now) in scenarios {
        let (req, inputs) = mk(expiry, now);
        out.push(PredicateCase {
            label: label.into(),
            body: PredicateBody {
                requirements: vec![req],
            },
            rust_eval: Box::new(move || diff_not_after_check(expiry, now)),
            inputs,
        });
    }
    out
}

fn cases_minimum_balance() -> Vec<PredicateCase> {
    // signature: (balance, threshold); requirement: balance >= threshold.
    let scenarios = [
        ("above-threshold", 500u64, 100u64),
        ("equal-threshold", 100, 100),
        ("below-threshold", 50, 100),
        ("zero-floor", 0, 0),
    ];
    scenarios
        .into_iter()
        .map(|(label, bal, thr)| PredicateCase {
            label: label.into(),
            body: PredicateBody {
                requirements: vec![Requirement::GreaterEqualU64(bal, thr)],
            },
            rust_eval: Box::new(move || diff_minimum_balance_check(bal, thr)),
            inputs: CaseInputs::new().u64("balance", bal).u64("threshold", thr),
        })
        .collect()
}

fn cases_exact_equal_u64() -> Vec<PredicateCase> {
    // signature: (expected, actual); requirement: expected == actual.
    let scenarios = [
        ("matching", 42u64, 42u64),
        ("differ-by-one", 42, 43),
        ("zero-zero", 0, 0),
        ("max-zero", u64::MAX, 0),
    ];
    scenarios
        .into_iter()
        .map(|(label, exp, act)| PredicateCase {
            label: label.into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualU64(exp, act)],
            },
            rust_eval: Box::new(move || diff_exact_equal_u64_check(exp, act)),
            inputs: CaseInputs::new().u64("expected", exp).u64("actual", act),
        })
        .collect()
}

fn cases_distinct_u64() -> Vec<PredicateCase> {
    // signature: (a, b); requirement: a != b.
    let scenarios = [
        ("distinct", 1u64, 2u64),
        ("identical", 7, 7),
        ("zero-zero", 0, 0),
    ];
    scenarios
        .into_iter()
        .map(|(label, a, b)| PredicateCase {
            label: label.into(),
            body: PredicateBody {
                requirements: vec![Requirement::NotEqualU64(a, b)],
            },
            rust_eval: Box::new(move || diff_distinct_u64_check(a, b)),
            inputs: CaseInputs::new().u64("a", a).u64("b", b),
        })
        .collect()
}

fn bytes_a() -> [u8; 32] {
    let mut b = [0u8; 32];
    for (i, slot) in b.iter_mut().enumerate() {
        *slot = i as u8;
    }
    b
}
fn bytes_b() -> [u8; 32] {
    let mut b = bytes_a();
    b[31] = 0xAA;
    b
}

fn cases_exact_equal_bytes() -> Vec<PredicateCase> {
    // signature: (expected, actual); requirement: expected == actual.
    let scenarios: [(&'static str, [u8; 32], [u8; 32]); 4] = [
        ("matching", bytes_a(), bytes_a()),
        ("differ-last-byte", bytes_a(), bytes_b()),
        ("all-zero", [0u8; 32], [0u8; 32]),
        ("all-ones", [0xFFu8; 32], [0xFFu8; 32]),
    ];
    scenarios
        .into_iter()
        .map(|(label, exp, act)| PredicateCase {
            label: label.into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualBytes32(exp, act)],
            },
            rust_eval: Box::new(move || diff_exact_equal_bytes_check(exp, act)),
            inputs: CaseInputs::new()
                .bytes("expected", exp)
                .bytes("actual", act),
        })
        .collect()
}

fn cases_distinct_bytes() -> Vec<PredicateCase> {
    // signature: (a, b); requirement: a != b.
    let scenarios: [(&'static str, [u8; 32], [u8; 32]); 2] = [
        ("distinct", bytes_a(), bytes_b()),
        ("identical", bytes_a(), bytes_a()),
    ];
    scenarios
        .into_iter()
        .map(|(label, a, b)| PredicateCase {
            label: label.into(),
            body: PredicateBody {
                requirements: vec![Requirement::NotEqualBytes32(a, b)],
            },
            rust_eval: Box::new(move || diff_distinct_bytes_check(a, b)),
            inputs: CaseInputs::new().bytes("a", a).bytes("b", b),
        })
        .collect()
}

fn cases_conjunction() -> Vec<PredicateCase> {
    // signature: (balance, threshold, sender, receiver); two requirements:
    // balance >= threshold AND sender != receiver.
    let scenarios = [
        ("both-ok", 500u64, 100u64, 1u64, 2u64),
        ("balance-too-low", 50, 100, 1, 2),
        ("same-party", 500, 100, 1, 1),
        ("both-fail", 50, 100, 1, 1),
    ];
    scenarios
        .into_iter()
        .map(|(label, bal, thr, snd, rcv)| PredicateCase {
            label: label.into(),
            body: PredicateBody {
                requirements: vec![
                    Requirement::GreaterEqualU64(bal, thr),
                    Requirement::NotEqualU64(snd, rcv),
                ],
            },
            rust_eval: Box::new(move || diff_conjunction_check(bal, thr, snd, rcv)),
            inputs: CaseInputs::new()
                .u64("balance", bal)
                .u64("threshold", thr)
                .u64("sender", snd)
                .u64("receiver", rcv),
        })
        .collect()
}

fn cases_window() -> Vec<PredicateCase> {
    // signature: (low, mid, high); two requirements: low <= mid AND mid <= high.
    let scenarios = [
        ("in-window", 0u64, 50u64, 100u64),
        ("tight-window", 10, 10, 10),
        ("below-window", 50, 25, 100),
        ("above-window", 0, 200, 100),
    ];
    scenarios
        .into_iter()
        .map(|(label, lo, mid, hi)| PredicateCase {
            label: label.into(),
            body: PredicateBody {
                requirements: vec![
                    Requirement::LessEqualU64(lo, mid),
                    Requirement::LessEqualU64(mid, hi),
                ],
            },
            rust_eval: Box::new(move || diff_window_check(lo, mid, hi)),
            inputs: CaseInputs::new()
                .u64("low", lo)
                .u64("mid", mid)
                .u64("high", hi),
        })
        .collect()
}

fn cases_set_member() -> Vec<PredicateCase> {
    // signature: (allowed, candidate); requirement: allowed.contains(candidate).
    let mut s: HashSet<u64> = HashSet::new();
    for v in [1u64, 5, 17, 42] {
        s.insert(v);
    }
    let empty: HashSet<u64> = HashSet::new();
    let cases = vec![
        ("member", s.clone(), 5u64),
        ("nonmember", s.clone(), 99),
        ("empty-set", empty, 5),
    ];
    cases
        .into_iter()
        .map(|(label, set_val, candidate)| {
            let set_for_rust = set_val.clone();
            let set_for_req = set_val.clone();
            PredicateCase {
                label: label.into(),
                body: PredicateBody {
                    requirements: vec![Requirement::Membership {
                        set: set_for_req,
                        element: candidate,
                    }],
                },
                rust_eval: Box::new(move || diff_set_member_check(&set_for_rust, candidate)),
                inputs: CaseInputs::new()
                    .set("allowed", set_val)
                    .u64("candidate", candidate),
            }
        })
        .collect()
}

fn cases_set_member_and_floor() -> Vec<PredicateCase> {
    // signature: (allowed, candidate, floor); two requirements:
    // allowed.contains(candidate) AND candidate >= floor.
    let mut s: HashSet<u64> = HashSet::new();
    for v in [10u64, 20, 30] {
        s.insert(v);
    }
    let scenarios = [
        ("member-above-floor", 20u64, 15u64),
        ("member-below-floor", 10, 15),
        ("nonmember-above-floor", 99, 15),
    ];
    scenarios
        .into_iter()
        .map(|(label, candidate, floor)| {
            let set_val = s.clone();
            let set_for_rust = set_val.clone();
            let set_for_req = set_val.clone();
            PredicateCase {
                label: label.into(),
                body: PredicateBody {
                    requirements: vec![
                        Requirement::Membership {
                            set: set_for_req,
                            element: candidate,
                        },
                        Requirement::GreaterEqualU64(candidate, floor),
                    ],
                },
                rust_eval: Box::new(move || {
                    diff_set_member_and_floor_check(&set_for_rust, candidate, floor)
                }),
                inputs: CaseInputs::new()
                    .set("allowed", set_val)
                    .u64("candidate", candidate)
                    .u64("floor", floor),
            }
        })
        .collect()
}

fn cases_triple_equal() -> Vec<PredicateCase> {
    // signature: (a, b, c); two requirements: a == b AND b == c.
    let scenarios = [
        ("all-equal", 7u64, 7u64, 7u64),
        ("first-mismatch", 7, 8, 8),
        ("second-mismatch", 5, 5, 9),
    ];
    scenarios
        .into_iter()
        .map(|(label, a, b, c)| PredicateCase {
            label: label.into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualU64(a, b), Requirement::EqualU64(b, c)],
            },
            rust_eval: Box::new(move || diff_triple_equal_check(a, b, c)),
            inputs: CaseInputs::new().u64("a", a).u64("b", b).u64("c", c),
        })
        .collect()
}

// ============================================================================
// Registry — referenced by tests::differential.
// ============================================================================

/// Static map of every predicate the harness drives. Two-step lookup
/// (`name` → `cases`) keeps the wiring simple in tests.
pub fn all_specs() -> Vec<PredicateSpec> {
    vec![
        PredicateSpec {
            name: "diff_not_after",
            cases: cases_not_after,
        },
        PredicateSpec {
            name: "diff_minimum_balance",
            cases: cases_minimum_balance,
        },
        PredicateSpec {
            name: "diff_exact_equal_u64",
            cases: cases_exact_equal_u64,
        },
        PredicateSpec {
            name: "diff_distinct_u64",
            cases: cases_distinct_u64,
        },
        PredicateSpec {
            name: "diff_exact_equal_bytes",
            cases: cases_exact_equal_bytes,
        },
        PredicateSpec {
            name: "diff_distinct_bytes",
            cases: cases_distinct_bytes,
        },
        PredicateSpec {
            name: "diff_conjunction",
            cases: cases_conjunction,
        },
        PredicateSpec {
            name: "diff_window",
            cases: cases_window,
        },
        PredicateSpec {
            name: "diff_set_member",
            cases: cases_set_member,
        },
        PredicateSpec {
            name: "diff_set_member_and_floor",
            cases: cases_set_member_and_floor,
        },
        PredicateSpec {
            name: "diff_triple_equal",
            cases: cases_triple_equal,
        },
    ]
}

// ============================================================================
// Backend-handle lookup.
// ============================================================================
//
// The DSL macros emit free functions like `diff_not_after_datalog()`. To
// avoid hard-coding string-match dispatch in every backend module, we expose
// a single `BackendHandles` struct per predicate so the simulators can look
// up the emitted artefacts by name.

pub struct BackendHandles {
    pub datalog_rule: &'static str,
    pub air: pyana_dsl_runtime::AirConstraintSet,
    pub kimchi: pyana_dsl_runtime::KimchiCircuitDescriptor,
    pub midnight_zkir: &'static str,
    pub sp1_guest: &'static str,
}

/// Resolve the emitted backend artefacts for a predicate.
///
/// We dispatch by name here because the DSL-emitted function identifiers
/// can't be invoked through a single trait impl without writing more
/// boilerplate than the dispatch saves.
pub fn lookup(name: &str) -> Option<BackendHandles> {
    Some(match name {
        "diff_not_after" => BackendHandles {
            datalog_rule: diff_not_after_datalog(),
            air: diff_not_after_air_constraints(),
            kimchi: diff_not_after_kimchi(),
            midnight_zkir: diff_not_after_midnight_zkir(),
            sp1_guest: diff_not_after_sp1_guest(),
        },
        "diff_minimum_balance" => BackendHandles {
            datalog_rule: diff_minimum_balance_datalog(),
            air: diff_minimum_balance_air_constraints(),
            kimchi: diff_minimum_balance_kimchi(),
            midnight_zkir: diff_minimum_balance_midnight_zkir(),
            sp1_guest: diff_minimum_balance_sp1_guest(),
        },
        "diff_exact_equal_u64" => BackendHandles {
            datalog_rule: diff_exact_equal_u64_datalog(),
            air: diff_exact_equal_u64_air_constraints(),
            kimchi: diff_exact_equal_u64_kimchi(),
            midnight_zkir: diff_exact_equal_u64_midnight_zkir(),
            sp1_guest: diff_exact_equal_u64_sp1_guest(),
        },
        "diff_distinct_u64" => BackendHandles {
            datalog_rule: diff_distinct_u64_datalog(),
            air: diff_distinct_u64_air_constraints(),
            kimchi: diff_distinct_u64_kimchi(),
            midnight_zkir: diff_distinct_u64_midnight_zkir(),
            sp1_guest: diff_distinct_u64_sp1_guest(),
        },
        "diff_exact_equal_bytes" => BackendHandles {
            datalog_rule: diff_exact_equal_bytes_datalog(),
            air: diff_exact_equal_bytes_air_constraints(),
            kimchi: diff_exact_equal_bytes_kimchi(),
            midnight_zkir: diff_exact_equal_bytes_midnight_zkir(),
            sp1_guest: diff_exact_equal_bytes_sp1_guest(),
        },
        "diff_distinct_bytes" => BackendHandles {
            datalog_rule: diff_distinct_bytes_datalog(),
            air: diff_distinct_bytes_air_constraints(),
            kimchi: diff_distinct_bytes_kimchi(),
            midnight_zkir: diff_distinct_bytes_midnight_zkir(),
            sp1_guest: diff_distinct_bytes_sp1_guest(),
        },
        "diff_conjunction" => BackendHandles {
            datalog_rule: diff_conjunction_datalog(),
            air: diff_conjunction_air_constraints(),
            kimchi: diff_conjunction_kimchi(),
            midnight_zkir: diff_conjunction_midnight_zkir(),
            sp1_guest: diff_conjunction_sp1_guest(),
        },
        "diff_window" => BackendHandles {
            datalog_rule: diff_window_datalog(),
            air: diff_window_air_constraints(),
            kimchi: diff_window_kimchi(),
            midnight_zkir: diff_window_midnight_zkir(),
            sp1_guest: diff_window_sp1_guest(),
        },
        "diff_set_member" => BackendHandles {
            datalog_rule: diff_set_member_datalog(),
            air: diff_set_member_air_constraints(),
            kimchi: diff_set_member_kimchi(),
            midnight_zkir: diff_set_member_midnight_zkir(),
            sp1_guest: diff_set_member_sp1_guest(),
        },
        "diff_set_member_and_floor" => BackendHandles {
            datalog_rule: diff_set_member_and_floor_datalog(),
            air: diff_set_member_and_floor_air_constraints(),
            kimchi: diff_set_member_and_floor_kimchi(),
            midnight_zkir: diff_set_member_and_floor_midnight_zkir(),
            sp1_guest: diff_set_member_and_floor_sp1_guest(),
        },
        "diff_triple_equal" => BackendHandles {
            datalog_rule: diff_triple_equal_datalog(),
            air: diff_triple_equal_air_constraints(),
            kimchi: diff_triple_equal_kimchi(),
            midnight_zkir: diff_triple_equal_midnight_zkir(),
            sp1_guest: diff_triple_equal_sp1_guest(),
        },
        _ => return None,
    })
}
