//! Canonical predicates exercised by the differential harness.
//!
//! Each predicate is defined twice:
//!
//! 1. Once via `#[pyana_caveat]` so the DSL emits the full backend zoo
//!    (`_check`, `_air_constraints`, `_datalog`, `_kimchi`, `_midnight_zkir`,
//!    `_sp1_guest`, plus the compile-time `{Name}P3Air` struct).
//! 2. Once via a [`PredicateSpec`] entry that captures (a) the predicate's
//!    canonical name, (b) its semantic shape encoded as
//!    [`PredicateBody`] so the kimchi/AIR/plonky3 simulators can render the
//!    same predicate into their own substrate, and (c) the curated input
//!    battery to drive through every backend.
//!
//! Why the dual definition? The Rust evaluator generated by `gen_rust` is the
//! ground truth — but the other backends emit topology (Kimchi gates, AIR
//! columns, ZKIR JSON) without an in-process verifier function. To
//! cross-check those backends we re-derive the same predicate semantically
//! using the IR-aligned helpers in `pyana_dsl_runtime::diff_witness` and the
//! shape-aware simulators in this crate. The dual definition is the price of
//! not requiring the SP1 toolchain or Midnight's proof server to run a test.

use std::collections::HashSet;

use pyana_dsl::pyana_caveat;
use pyana_dsl_runtime::ConstraintError;

// ============================================================================
// DSL caveat definitions (the canonical source of truth for each predicate).
// ============================================================================
//
// Pre-edition note: pyana_caveat parses the function body and emits the
// matching backends. The bodies below MUST stay simple enough that all
// backends accept them; if you add a body with no IR support in one backend,
// that backend will be reported as Skip(reason) downstream.

#[pyana_caveat]
fn diff_not_after(token_expiry: u64, current_time: u64) {
    require!(current_time <= token_expiry);
}

#[pyana_caveat]
fn diff_minimum_balance(balance: u64, threshold: u64) {
    require!(balance >= threshold);
}

#[pyana_caveat]
fn diff_exact_equal_u64(expected: u64, actual: u64) {
    require!(expected == actual);
}

#[pyana_caveat]
fn diff_distinct_u64(a: u64, b: u64) {
    require!(a != b);
}

#[pyana_caveat]
fn diff_exact_equal_bytes(expected: [u8; 32], actual: [u8; 32]) {
    require!(expected == actual);
}

#[pyana_caveat]
fn diff_distinct_bytes(a: [u8; 32], b: [u8; 32]) {
    require!(a != b);
}

#[pyana_caveat]
fn diff_conjunction(balance: u64, threshold: u64, sender: u64, receiver: u64) {
    require!(balance >= threshold);
    require!(sender != receiver);
}

#[pyana_caveat]
fn diff_window(low: u64, mid: u64, high: u64) {
    require!(low <= mid);
    require!(mid <= high);
}

#[pyana_caveat]
fn diff_set_member(allowed: &std::collections::HashSet<u64>, candidate: u64) {
    require!(allowed.contains(candidate));
}

#[pyana_caveat]
fn diff_set_member_and_floor(allowed: &std::collections::HashSet<u64>, candidate: u64, floor: u64) {
    require!(allowed.contains(candidate));
    require!(candidate >= floor);
}

#[pyana_caveat]
fn diff_triple_equal(a: u64, b: u64, c: u64) {
    require!(a == b);
    require!(b == c);
}

// ============================================================================
// Semantic shape catalog
// ============================================================================

/// A single requirement comparable by all backends. Kept separate from
/// `pyana_dsl::ir` (which is internal to the proc-macro crate) so this crate
/// can stand alone.
#[derive(Clone)]
pub enum Requirement {
    LessEqualU64(u64, u64),
    GreaterEqualU64(u64, u64),
    EqualU64(u64, u64),
    NotEqualU64(u64, u64),
    EqualBytes32([u8; 32], [u8; 32]),
    NotEqualBytes32([u8; 32], [u8; 32]),
    Membership { set: HashSet<u64>, element: u64 },
}

impl std::fmt::Debug for Requirement {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::LessEqualU64(l, r) => write!(f, "LessEqualU64({l}, {r})"),
            Self::GreaterEqualU64(l, r) => write!(f, "GreaterEqualU64({l}, {r})"),
            Self::EqualU64(l, r) => write!(f, "EqualU64({l}, {r})"),
            Self::NotEqualU64(l, r) => write!(f, "NotEqualU64({l}, {r})"),
            Self::EqualBytes32(_, _) => write!(f, "EqualBytes32(.., ..)"),
            Self::NotEqualBytes32(_, _) => write!(f, "NotEqualBytes32(.., ..)"),
            Self::Membership { set, element } => {
                write!(f, "Membership(|set|={}, element={element})", set.len())
            }
        }
    }
}

impl Requirement {
    /// The IR-level truth of this requirement.
    pub fn holds(&self) -> bool {
        match self {
            Self::LessEqualU64(l, r) => l <= r,
            Self::GreaterEqualU64(l, r) => l >= r,
            Self::EqualU64(l, r) => l == r,
            Self::NotEqualU64(l, r) => l != r,
            Self::EqualBytes32(l, r) => l == r,
            Self::NotEqualBytes32(l, r) => l != r,
            Self::Membership { set, element } => set.contains(element),
        }
    }
}

/// The body of a predicate as a conjunction of requirements (all backends
/// fail-fast on the first unsatisfied requirement, matching how the
/// generated `{name}_check` is emitted).
#[derive(Debug, Clone)]
pub struct PredicateBody {
    pub requirements: Vec<Requirement>,
}

impl PredicateBody {
    pub fn holds(&self) -> bool {
        self.requirements.iter().all(|r| r.holds())
    }
}

/// One full case: a body bound to concrete inputs, plus a label for
/// disagreement reports.
pub struct PredicateCase {
    pub label: String,
    pub body: PredicateBody,
    /// Direct invocation of the `gen_rust` evaluator for this predicate's
    /// inputs. Returning `Ok(())` means "accept", `Err(_)` means "reject".
    pub rust_eval: Box<dyn Fn() -> Result<(), ConstraintError>>,
}

/// One predicate definition: its canonical name, the IR-shape catalog of
/// its body (which all simulators consult), and the input battery.
pub struct PredicateSpec {
    pub name: &'static str,
    /// Lazy thunk producing the case battery. Owns its own `HashSet`s.
    pub cases: fn() -> Vec<PredicateCase>,
}

// ============================================================================
// Case batteries: each one binds the `#[pyana_caveat]`-generated `_check`
// against the same data fed to the IR-shape simulators downstream.
// ============================================================================

fn cases_not_after() -> Vec<PredicateCase> {
    vec![
        PredicateCase {
            label: "expiry-in-future".into(),
            body: PredicateBody {
                requirements: vec![Requirement::LessEqualU64(50, 100)],
            },
            rust_eval: Box::new(|| diff_not_after_check(100, 50)),
        },
        PredicateCase {
            label: "expiry-equal".into(),
            body: PredicateBody {
                requirements: vec![Requirement::LessEqualU64(100, 100)],
            },
            rust_eval: Box::new(|| diff_not_after_check(100, 100)),
        },
        PredicateCase {
            label: "expiry-past".into(),
            body: PredicateBody {
                requirements: vec![Requirement::LessEqualU64(101, 100)],
            },
            rust_eval: Box::new(|| diff_not_after_check(100, 101)),
        },
        PredicateCase {
            label: "boundary-zero".into(),
            body: PredicateBody {
                requirements: vec![Requirement::LessEqualU64(0, 0)],
            },
            rust_eval: Box::new(|| diff_not_after_check(0, 0)),
        },
        PredicateCase {
            label: "boundary-max".into(),
            body: PredicateBody {
                requirements: vec![Requirement::LessEqualU64(u64::MAX, u64::MAX)],
            },
            rust_eval: Box::new(|| diff_not_after_check(u64::MAX, u64::MAX)),
        },
        PredicateCase {
            label: "near-overflow-reject".into(),
            body: PredicateBody {
                requirements: vec![Requirement::LessEqualU64(u64::MAX, u64::MAX - 1)],
            },
            rust_eval: Box::new(|| diff_not_after_check(u64::MAX - 1, u64::MAX)),
        },
    ]
}

fn cases_minimum_balance() -> Vec<PredicateCase> {
    vec![
        PredicateCase {
            label: "above-threshold".into(),
            body: PredicateBody {
                requirements: vec![Requirement::GreaterEqualU64(500, 100)],
            },
            rust_eval: Box::new(|| diff_minimum_balance_check(500, 100)),
        },
        PredicateCase {
            label: "equal-threshold".into(),
            body: PredicateBody {
                requirements: vec![Requirement::GreaterEqualU64(100, 100)],
            },
            rust_eval: Box::new(|| diff_minimum_balance_check(100, 100)),
        },
        PredicateCase {
            label: "below-threshold".into(),
            body: PredicateBody {
                requirements: vec![Requirement::GreaterEqualU64(50, 100)],
            },
            rust_eval: Box::new(|| diff_minimum_balance_check(50, 100)),
        },
        PredicateCase {
            label: "zero-floor".into(),
            body: PredicateBody {
                requirements: vec![Requirement::GreaterEqualU64(0, 0)],
            },
            rust_eval: Box::new(|| diff_minimum_balance_check(0, 0)),
        },
    ]
}

fn cases_exact_equal_u64() -> Vec<PredicateCase> {
    vec![
        PredicateCase {
            label: "matching".into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualU64(42, 42)],
            },
            rust_eval: Box::new(|| diff_exact_equal_u64_check(42, 42)),
        },
        PredicateCase {
            label: "differ-by-one".into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualU64(42, 43)],
            },
            rust_eval: Box::new(|| diff_exact_equal_u64_check(42, 43)),
        },
        PredicateCase {
            label: "zero-zero".into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualU64(0, 0)],
            },
            rust_eval: Box::new(|| diff_exact_equal_u64_check(0, 0)),
        },
        PredicateCase {
            label: "max-zero".into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualU64(u64::MAX, 0)],
            },
            rust_eval: Box::new(|| diff_exact_equal_u64_check(u64::MAX, 0)),
        },
    ]
}

fn cases_distinct_u64() -> Vec<PredicateCase> {
    vec![
        PredicateCase {
            label: "distinct".into(),
            body: PredicateBody {
                requirements: vec![Requirement::NotEqualU64(1, 2)],
            },
            rust_eval: Box::new(|| diff_distinct_u64_check(1, 2)),
        },
        PredicateCase {
            label: "identical".into(),
            body: PredicateBody {
                requirements: vec![Requirement::NotEqualU64(7, 7)],
            },
            rust_eval: Box::new(|| diff_distinct_u64_check(7, 7)),
        },
        PredicateCase {
            label: "zero-zero".into(),
            body: PredicateBody {
                requirements: vec![Requirement::NotEqualU64(0, 0)],
            },
            rust_eval: Box::new(|| diff_distinct_u64_check(0, 0)),
        },
    ]
}

fn bytes_a() -> [u8; 32] {
    let mut b = [0u8; 32];
    for (i, slot) in b.iter_mut().enumerate() {
        *slot = i as u8;
    }
    b
}
fn bytes_b() -> [u8; 32] {
    let mut b = bytes_a();
    b[31] = 0xAA;
    b
}

fn cases_exact_equal_bytes() -> Vec<PredicateCase> {
    vec![
        PredicateCase {
            label: "matching".into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualBytes32(bytes_a(), bytes_a())],
            },
            rust_eval: Box::new(|| diff_exact_equal_bytes_check(bytes_a(), bytes_a())),
        },
        PredicateCase {
            label: "differ-last-byte".into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualBytes32(bytes_a(), bytes_b())],
            },
            rust_eval: Box::new(|| diff_exact_equal_bytes_check(bytes_a(), bytes_b())),
        },
        PredicateCase {
            label: "all-zero".into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualBytes32([0u8; 32], [0u8; 32])],
            },
            rust_eval: Box::new(|| diff_exact_equal_bytes_check([0u8; 32], [0u8; 32])),
        },
        PredicateCase {
            label: "all-ones".into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualBytes32([0xFFu8; 32], [0xFFu8; 32])],
            },
            rust_eval: Box::new(|| diff_exact_equal_bytes_check([0xFFu8; 32], [0xFFu8; 32])),
        },
    ]
}

fn cases_distinct_bytes() -> Vec<PredicateCase> {
    vec![
        PredicateCase {
            label: "distinct".into(),
            body: PredicateBody {
                requirements: vec![Requirement::NotEqualBytes32(bytes_a(), bytes_b())],
            },
            rust_eval: Box::new(|| diff_distinct_bytes_check(bytes_a(), bytes_b())),
        },
        PredicateCase {
            label: "identical".into(),
            body: PredicateBody {
                requirements: vec![Requirement::NotEqualBytes32(bytes_a(), bytes_a())],
            },
            rust_eval: Box::new(|| diff_distinct_bytes_check(bytes_a(), bytes_a())),
        },
    ]
}

fn cases_conjunction() -> Vec<PredicateCase> {
    vec![
        PredicateCase {
            label: "both-ok".into(),
            body: PredicateBody {
                requirements: vec![
                    Requirement::GreaterEqualU64(500, 100),
                    Requirement::NotEqualU64(1, 2),
                ],
            },
            rust_eval: Box::new(|| diff_conjunction_check(500, 100, 1, 2)),
        },
        PredicateCase {
            label: "balance-too-low".into(),
            body: PredicateBody {
                requirements: vec![
                    Requirement::GreaterEqualU64(50, 100),
                    Requirement::NotEqualU64(1, 2),
                ],
            },
            rust_eval: Box::new(|| diff_conjunction_check(50, 100, 1, 2)),
        },
        PredicateCase {
            label: "same-party".into(),
            body: PredicateBody {
                requirements: vec![
                    Requirement::GreaterEqualU64(500, 100),
                    Requirement::NotEqualU64(1, 1),
                ],
            },
            rust_eval: Box::new(|| diff_conjunction_check(500, 100, 1, 1)),
        },
        PredicateCase {
            label: "both-fail".into(),
            body: PredicateBody {
                requirements: vec![
                    Requirement::GreaterEqualU64(50, 100),
                    Requirement::NotEqualU64(1, 1),
                ],
            },
            rust_eval: Box::new(|| diff_conjunction_check(50, 100, 1, 1)),
        },
    ]
}

fn cases_window() -> Vec<PredicateCase> {
    vec![
        PredicateCase {
            label: "in-window".into(),
            body: PredicateBody {
                requirements: vec![
                    Requirement::LessEqualU64(0, 50),
                    Requirement::LessEqualU64(50, 100),
                ],
            },
            rust_eval: Box::new(|| diff_window_check(0, 50, 100)),
        },
        PredicateCase {
            label: "tight-window".into(),
            body: PredicateBody {
                requirements: vec![
                    Requirement::LessEqualU64(10, 10),
                    Requirement::LessEqualU64(10, 10),
                ],
            },
            rust_eval: Box::new(|| diff_window_check(10, 10, 10)),
        },
        PredicateCase {
            label: "below-window".into(),
            body: PredicateBody {
                requirements: vec![
                    Requirement::LessEqualU64(50, 25),
                    Requirement::LessEqualU64(25, 100),
                ],
            },
            rust_eval: Box::new(|| diff_window_check(50, 25, 100)),
        },
        PredicateCase {
            label: "above-window".into(),
            body: PredicateBody {
                requirements: vec![
                    Requirement::LessEqualU64(0, 200),
                    Requirement::LessEqualU64(200, 100),
                ],
            },
            rust_eval: Box::new(|| diff_window_check(0, 200, 100)),
        },
    ]
}

fn cases_set_member() -> Vec<PredicateCase> {
    let mut s = HashSet::new();
    for v in [1u64, 5, 17, 42] {
        s.insert(v);
    }
    let s2 = s.clone();
    let s3 = s.clone();
    let s_empty: HashSet<u64> = HashSet::new();
    let s_empty2 = s_empty.clone();
    vec![
        PredicateCase {
            label: "member".into(),
            body: PredicateBody {
                requirements: vec![Requirement::Membership {
                    set: s.clone(),
                    element: 5,
                }],
            },
            rust_eval: Box::new(move || diff_set_member_check(&s2, 5)),
        },
        PredicateCase {
            label: "nonmember".into(),
            body: PredicateBody {
                requirements: vec![Requirement::Membership {
                    set: s.clone(),
                    element: 99,
                }],
            },
            rust_eval: Box::new(move || diff_set_member_check(&s3, 99)),
        },
        PredicateCase {
            label: "empty-set".into(),
            body: PredicateBody {
                requirements: vec![Requirement::Membership {
                    set: s_empty.clone(),
                    element: 5,
                }],
            },
            rust_eval: Box::new(move || diff_set_member_check(&s_empty2, 5)),
        },
    ]
}

fn cases_set_member_and_floor() -> Vec<PredicateCase> {
    let mut s = HashSet::new();
    for v in [10u64, 20, 30] {
        s.insert(v);
    }
    let s2 = s.clone();
    let s3 = s.clone();
    let s4 = s.clone();
    vec![
        PredicateCase {
            label: "member-above-floor".into(),
            body: PredicateBody {
                requirements: vec![
                    Requirement::Membership {
                        set: s.clone(),
                        element: 20,
                    },
                    Requirement::GreaterEqualU64(20, 15),
                ],
            },
            rust_eval: Box::new(move || diff_set_member_and_floor_check(&s2, 20, 15)),
        },
        PredicateCase {
            label: "member-below-floor".into(),
            body: PredicateBody {
                requirements: vec![
                    Requirement::Membership {
                        set: s.clone(),
                        element: 10,
                    },
                    Requirement::GreaterEqualU64(10, 15),
                ],
            },
            rust_eval: Box::new(move || diff_set_member_and_floor_check(&s3, 10, 15)),
        },
        PredicateCase {
            label: "nonmember-above-floor".into(),
            body: PredicateBody {
                requirements: vec![
                    Requirement::Membership {
                        set: s.clone(),
                        element: 99,
                    },
                    Requirement::GreaterEqualU64(99, 15),
                ],
            },
            rust_eval: Box::new(move || diff_set_member_and_floor_check(&s4, 99, 15)),
        },
    ]
}

fn cases_triple_equal() -> Vec<PredicateCase> {
    vec![
        PredicateCase {
            label: "all-equal".into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualU64(7, 7), Requirement::EqualU64(7, 7)],
            },
            rust_eval: Box::new(|| diff_triple_equal_check(7, 7, 7)),
        },
        PredicateCase {
            label: "first-mismatch".into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualU64(7, 8), Requirement::EqualU64(8, 8)],
            },
            rust_eval: Box::new(|| diff_triple_equal_check(7, 8, 8)),
        },
        PredicateCase {
            label: "second-mismatch".into(),
            body: PredicateBody {
                requirements: vec![Requirement::EqualU64(5, 5), Requirement::EqualU64(5, 9)],
            },
            rust_eval: Box::new(|| diff_triple_equal_check(5, 5, 9)),
        },
    ]
}

// ============================================================================
// Registry — referenced by tests::differential.
// ============================================================================

/// Static map of every predicate the harness drives. Two-step lookup
/// (`name` → `cases`) keeps the wiring simple in tests.
pub fn all_specs() -> Vec<PredicateSpec> {
    vec![
        PredicateSpec {
            name: "diff_not_after",
            cases: cases_not_after,
        },
        PredicateSpec {
            name: "diff_minimum_balance",
            cases: cases_minimum_balance,
        },
        PredicateSpec {
            name: "diff_exact_equal_u64",
            cases: cases_exact_equal_u64,
        },
        PredicateSpec {
            name: "diff_distinct_u64",
            cases: cases_distinct_u64,
        },
        PredicateSpec {
            name: "diff_exact_equal_bytes",
            cases: cases_exact_equal_bytes,
        },
        PredicateSpec {
            name: "diff_distinct_bytes",
            cases: cases_distinct_bytes,
        },
        PredicateSpec {
            name: "diff_conjunction",
            cases: cases_conjunction,
        },
        PredicateSpec {
            name: "diff_window",
            cases: cases_window,
        },
        PredicateSpec {
            name: "diff_set_member",
            cases: cases_set_member,
        },
        PredicateSpec {
            name: "diff_set_member_and_floor",
            cases: cases_set_member_and_floor,
        },
        PredicateSpec {
            name: "diff_triple_equal",
            cases: cases_triple_equal,
        },
    ]
}

// ============================================================================
// Backend-handle lookup.
// ============================================================================
//
// The DSL macros emit free functions like `diff_not_after_datalog()`. To
// avoid hard-coding string-match dispatch in every backend module, we expose
// a single `BackendHandles` struct per predicate so the simulators can look
// up the emitted artefacts by name.

pub struct BackendHandles {
    pub datalog_rule: &'static str,
    pub air: pyana_dsl_runtime::AirConstraintSet,
    pub kimchi: pyana_dsl_runtime::KimchiCircuitDescriptor,
    pub midnight_zkir: &'static str,
    pub sp1_guest: &'static str,
}

/// Resolve the emitted backend artefacts for a predicate.
///
/// We dispatch by name here because the DSL-emitted function identifiers
/// can't be invoked through a single trait impl without writing more
/// boilerplate than the dispatch saves.
pub fn lookup(name: &str) -> Option<BackendHandles> {
    Some(match name {
        "diff_not_after" => BackendHandles {
            datalog_rule: diff_not_after_datalog(),
            air: diff_not_after_air_constraints(),
            kimchi: diff_not_after_kimchi(),
            midnight_zkir: diff_not_after_midnight_zkir(),
            sp1_guest: diff_not_after_sp1_guest(),
        },
        "diff_minimum_balance" => BackendHandles {
            datalog_rule: diff_minimum_balance_datalog(),
            air: diff_minimum_balance_air_constraints(),
            kimchi: diff_minimum_balance_kimchi(),
            midnight_zkir: diff_minimum_balance_midnight_zkir(),
            sp1_guest: diff_minimum_balance_sp1_guest(),
        },
        "diff_exact_equal_u64" => BackendHandles {
            datalog_rule: diff_exact_equal_u64_datalog(),
            air: diff_exact_equal_u64_air_constraints(),
            kimchi: diff_exact_equal_u64_kimchi(),
            midnight_zkir: diff_exact_equal_u64_midnight_zkir(),
            sp1_guest: diff_exact_equal_u64_sp1_guest(),
        },
        "diff_distinct_u64" => BackendHandles {
            datalog_rule: diff_distinct_u64_datalog(),
            air: diff_distinct_u64_air_constraints(),
            kimchi: diff_distinct_u64_kimchi(),
            midnight_zkir: diff_distinct_u64_midnight_zkir(),
            sp1_guest: diff_distinct_u64_sp1_guest(),
        },
        "diff_exact_equal_bytes" => BackendHandles {
            datalog_rule: diff_exact_equal_bytes_datalog(),
            air: diff_exact_equal_bytes_air_constraints(),
            kimchi: diff_exact_equal_bytes_kimchi(),
            midnight_zkir: diff_exact_equal_bytes_midnight_zkir(),
            sp1_guest: diff_exact_equal_bytes_sp1_guest(),
        },
        "diff_distinct_bytes" => BackendHandles {
            datalog_rule: diff_distinct_bytes_datalog(),
            air: diff_distinct_bytes_air_constraints(),
            kimchi: diff_distinct_bytes_kimchi(),
            midnight_zkir: diff_distinct_bytes_midnight_zkir(),
            sp1_guest: diff_distinct_bytes_sp1_guest(),
        },
        "diff_conjunction" => BackendHandles {
            datalog_rule: diff_conjunction_datalog(),
            air: diff_conjunction_air_constraints(),
            kimchi: diff_conjunction_kimchi(),
            midnight_zkir: diff_conjunction_midnight_zkir(),
            sp1_guest: diff_conjunction_sp1_guest(),
        },
        "diff_window" => BackendHandles {
            datalog_rule: diff_window_datalog(),
            air: diff_window_air_constraints(),
            kimchi: diff_window_kimchi(),
            midnight_zkir: diff_window_midnight_zkir(),
            sp1_guest: diff_window_sp1_guest(),
        },
        "diff_set_member" => BackendHandles {
            datalog_rule: diff_set_member_datalog(),
            air: diff_set_member_air_constraints(),
            kimchi: diff_set_member_kimchi(),
            midnight_zkir: diff_set_member_midnight_zkir(),
            sp1_guest: diff_set_member_sp1_guest(),
        },
        "diff_set_member_and_floor" => BackendHandles {
            datalog_rule: diff_set_member_and_floor_datalog(),
            air: diff_set_member_and_floor_air_constraints(),
            kimchi: diff_set_member_and_floor_kimchi(),
            midnight_zkir: diff_set_member_and_floor_midnight_zkir(),
            sp1_guest: diff_set_member_and_floor_sp1_guest(),
        },
        "diff_triple_equal" => BackendHandles {
            datalog_rule: diff_triple_equal_datalog(),
            air: diff_triple_equal_air_constraints(),
            kimchi: diff_triple_equal_kimchi(),
            midnight_zkir: diff_triple_equal_midnight_zkir(),
            sp1_guest: diff_triple_equal_sp1_guest(),
        },
        _ => return None,
    })
}
