//! Poseidon2 hash function over BabyBear with proven parameters from Plonky3.
//!
//! Parameters sourced from `p3-baby-bear` (Plonky3 repository) with 128-bit
//! security proofs from the Poseidon2 paper (https://eprint.iacr.org/2023/323).
//!
//! Configuration:
//! - Field: BabyBear (p = 2^31 - 2^27 + 1)
//! - Width: 16 field elements
//! - S-box: x^7
//! - External (full) rounds: 8 (4 initial + 4 final)
//! - Internal (partial) rounds: 13
//! - External linear layer: MDSMat4 circulant [2,3,1,1] applied blockwise
//! - Internal linear layer: 1 + Diag(V) where V is optimized for BabyBear
//!
//! Round constants generated by the Grain LFSR with parameters:
//!   field_type=1, alpha=7 (exp_flag=0), n=31, t=16, R_F=8, R_P=13

use crate::field::BabyBear;

/// Poseidon2 state width (number of field elements in state).
pub const WIDTH: usize = 16;

/// Number of external (full) rounds.
pub const EXTERNAL_ROUNDS: usize = 8;

/// Number of internal (partial) rounds.
pub const INTERNAL_ROUNDS: usize = 13;

/// Total rounds.
pub const TOTAL_ROUNDS: usize = EXTERNAL_ROUNDS + INTERNAL_ROUNDS;

/// S-box exponent for BabyBear (x^7).
const SBOX_ALPHA: u32 = 7;

/// Initial external round constants (4 rounds x 16 elements).
/// From BABYBEAR_POSEIDON2_RC_16_EXTERNAL_INITIAL in p3-baby-bear.
const RC_EXT_INIT: [[u32; 16]; 4] = [
    [
        0x69cbb6af, 0x46ad93f9, 0x60a00f4e, 0x6b1297cd, 0x23189afe, 0x732e7bef, 0x72c246de,
        0x2c941900, 0x0557eede, 0x1580496f, 0x3a3ea77b, 0x54f3f271, 0x0f49b029, 0x47872fe1,
        0x221e2e36, 0x1ab7202e,
    ],
    [
        0x487779a6, 0x3851c9d8, 0x38dc17c0, 0x209f8849, 0x268dcee8, 0x350c48da, 0x5b9ad32e,
        0x0523272b, 0x3f89055b, 0x01e894b2, 0x13ddedde, 0x1b2ef334, 0x7507d8b4, 0x6ceeb94e,
        0x52eb6ba2, 0x50642905,
    ],
    [
        0x05453f3f, 0x06349efc, 0x6922787c, 0x04bfff9c, 0x768c714a, 0x3e9ff21a, 0x15737c9c,
        0x2229c807, 0x0d47f88c, 0x097e0ecc, 0x27eadba0, 0x2d7d29e4, 0x3502aaa0, 0x0f475fd7,
        0x29fbda49, 0x018afffd,
    ],
    [
        0x0315b618, 0x6d4497d1, 0x1b171d9e, 0x52861abd, 0x2e5d0501, 0x3ec8646c, 0x6e5f250a,
        0x148ae8e6, 0x17f5fa4a, 0x3e66d284, 0x0051aa3b, 0x483f7913, 0x2cfe5f15, 0x023427ca,
        0x2cc78315, 0x1e36ea47,
    ],
];

/// Final external round constants (4 rounds x 16 elements).
const RC_EXT_FINAL: [[u32; 16]; 4] = [
    [
        0x7290a80d, 0x6f7e5329, 0x598ec8a8, 0x76a859a0, 0x6559e868, 0x657b83af, 0x13271d3f,
        0x1f876063, 0x0aeeae37, 0x706e9ca6, 0x46400cee, 0x72a05c26, 0x2c589c9e, 0x20bd37a7,
        0x6a2d3d10, 0x20523767,
    ],
    [
        0x5b8fe9c4, 0x2aa501d6, 0x1e01ac3e, 0x1448bc54, 0x5ce5ad1c, 0x4918a14d, 0x2c46a83f,
        0x4fcf6876, 0x61d8d5c8, 0x6ddf4ff9, 0x11fda4d3, 0x02933a8f, 0x170eaf81, 0x5a9c314f,
        0x49a12590, 0x35ec52a1,
    ],
    [
        0x58eb1611, 0x5e481e65, 0x367125c9, 0x0eba33ba, 0x1fc28ded, 0x066399ad, 0x0cbec0ea,
        0x75fd1af0, 0x50f5bf4e, 0x643d5f41, 0x6f4fe718, 0x5b3cbbde, 0x1e3afb3e, 0x296fb027,
        0x45e1547b, 0x4a8db2ab,
    ],
    [
        0x59986d19, 0x30bcdfa3, 0x1db63932, 0x1d7c2824, 0x53b33681, 0x0673b747, 0x038a98a3,
        0x2c5bce60, 0x351979cd, 0x5008fb73, 0x547bca78, 0x711af481, 0x3f93bf64, 0x644d987b,
        0x3c8bcd87, 0x608758b8,
    ],
];

/// Internal round constants (13 scalars). From BABYBEAR_POSEIDON2_RC_16_INTERNAL.
const RC_INTERNAL: [u32; 13] = [
    0x5a8053c0, 0x693be639, 0x3858867d, 0x19334f6b, 0x128f0fd8, 0x4e2b1ccb, 0x61210ce0, 0x3c318939,
    0x0b5b2f22, 0x2edb11d5, 0x213effdf, 0x0cac4606, 0x241af16d,
];

/// Internal diagonal d_i = 1 + V[i].
/// V = [-2, 1, 2, 1/2, 3, 4, -1/2, -3, -4, 1/2^8, 1/4, 1/8, 1/2^27, -1/2^8, -1/16, -1/2^27]
pub static INTERNAL_DIAG: [BabyBear; WIDTH] = [
    BabyBear(2013265920),
    BabyBear(2),
    BabyBear(3),
    BabyBear(1006632962),
    BabyBear(4),
    BabyBear(5),
    BabyBear(1006632961),
    BabyBear(2013265919),
    BabyBear(2013265918),
    BabyBear(2005401602),
    BabyBear(1509949442),
    BabyBear(1761607682),
    BabyBear(2013265907),
    BabyBear(7864321),
    BabyBear(125829121),
    BabyBear(16),
];

/// Cached round constants from Plonky3 Grain LFSR derivation.
pub static ROUND_CONSTANTS: std::sync::LazyLock<Vec<[BabyBear; WIDTH]>> =
    std::sync::LazyLock::new(compute_round_constants);

fn compute_round_constants() -> Vec<[BabyBear; WIDTH]> {
    let mut constants = Vec::with_capacity(TOTAL_ROUNDS);
    for round in 0..EXTERNAL_ROUNDS / 2 {
        let mut rc = [BabyBear::ZERO; WIDTH];
        for j in 0..WIDTH {
            rc[j] = BabyBear::new(RC_EXT_INIT[round][j]);
        }
        constants.push(rc);
    }
    for round in 0..INTERNAL_ROUNDS {
        let mut rc = [BabyBear::ZERO; WIDTH];
        rc[0] = BabyBear::new(RC_INTERNAL[round]);
        constants.push(rc);
    }
    for round in 0..EXTERNAL_ROUNDS / 2 {
        let mut rc = [BabyBear::ZERO; WIDTH];
        for j in 0..WIDTH {
            rc[j] = BabyBear::new(RC_EXT_FINAL[round][j]);
        }
        constants.push(rc);
    }
    constants
}

/// The Poseidon2 permutation state.
#[derive(Clone, Debug)]
pub struct Poseidon2State {
    pub state: [BabyBear; WIDTH],
}

impl Poseidon2State {
    /// Create a new state initialized to zero.
    pub fn new() -> Self {
        Self {
            state: [BabyBear::ZERO; WIDTH],
        }
    }

    /// Create a state from field elements (remaining positions zero-padded).
    pub fn from_elements(elements: &[BabyBear]) -> Self {
        let mut state = [BabyBear::ZERO; WIDTH];
        for (i, &e) in elements.iter().take(WIDTH).enumerate() {
            state[i] = e;
        }
        Self { state }
    }

    /// Apply the S-box: x -> x^7.
    #[inline]
    pub fn sbox(x: BabyBear) -> BabyBear {
        x.pow(SBOX_ALPHA)
    }

    /// Apply the external linear layer: MDSMat4 [2,3,1,1] applied blockwise + wider.
    pub fn external_linear_layer(&mut self) {
        // Apply 4x4 MDS to each chunk of 4
        for cs in (0..WIDTH).step_by(4) {
            let (x0, x1, x2, x3) = (
                self.state[cs],
                self.state[cs + 1],
                self.state[cs + 2],
                self.state[cs + 3],
            );
            let t01 = x0 + x1;
            let t23 = x2 + x3;
            let t0123 = t01 + t23;
            let t01123 = t0123 + x1;
            let t01233 = t0123 + x3;
            self.state[cs] = t01123 + t01; // 2x0+3x1+x2+x3
            self.state[cs + 1] = t01123 + x2 + x2; // x0+2x1+3x2+x3
            self.state[cs + 2] = t01233 + t23; // x0+x1+2x2+3x3
            self.state[cs + 3] = t01233 + x0 + x0; // 3x0+x1+x2+2x3
        }
        // Wider: add column sums
        let mut sums = [BabyBear::ZERO; 4];
        for k in 0..4 {
            for j in (0..WIDTH).step_by(4) {
                sums[k] = sums[k] + self.state[j + k];
            }
        }
        for i in 0..WIDTH {
            self.state[i] = self.state[i] + sums[i % 4];
        }
    }

    /// Apply the internal linear layer: (1 + Diag(V)) * x.
    /// x_i' = sum(x) + (d_i - 1) * x_i
    pub fn internal_linear_layer(&mut self) {
        let diag = &INTERNAL_DIAG;
        let sum: BabyBear = self
            .state
            .iter()
            .copied()
            .fold(BabyBear::ZERO, |a, b| a + b);
        for i in 0..WIDTH {
            self.state[i] = sum + (diag[i] - BabyBear::ONE) * self.state[i];
        }
    }

    /// Apply the full Poseidon2 permutation.
    pub fn permute(&mut self) {
        let rc = &*ROUND_CONSTANTS;

        // Initial linear layer (per Poseidon2 spec)
        self.external_linear_layer();

        // First half of external rounds
        for round in 0..EXTERNAL_ROUNDS / 2 {
            // Add round constants
            for i in 0..WIDTH {
                self.state[i] += rc[round][i];
            }
            // Full S-box layer
            for i in 0..WIDTH {
                self.state[i] = Self::sbox(self.state[i]);
            }
            // External linear layer
            self.external_linear_layer();
        }

        // Internal rounds
        for round in 0..INTERNAL_ROUNDS {
            let rc_idx = EXTERNAL_ROUNDS / 2 + round;
            // Add round constant to first element only
            self.state[0] += rc[rc_idx][0];
            // Partial S-box (only first element)
            self.state[0] = Self::sbox(self.state[0]);
            // Internal linear layer
            self.internal_linear_layer();
        }

        // Second half of external rounds
        for round in 0..EXTERNAL_ROUNDS / 2 {
            let rc_idx = EXTERNAL_ROUNDS / 2 + INTERNAL_ROUNDS + round;
            // Add round constants
            for i in 0..WIDTH {
                self.state[i] += rc[rc_idx][i];
            }
            // Full S-box layer
            for i in 0..WIDTH {
                self.state[i] = Self::sbox(self.state[i]);
            }
            // External linear layer
            self.external_linear_layer();
        }
    }
}

/// Apply the external linear layer to a state array (standalone version).
pub fn apply_external_linear_layer(state: &[BabyBear; WIDTH]) -> [BabyBear; WIDTH] {
    let mut ps = Poseidon2State { state: *state };
    ps.external_linear_layer();
    ps.state
}

/// Apply the internal linear layer to a state array (standalone version).
pub fn apply_internal_linear_layer(state: &[BabyBear; WIDTH]) -> [BabyBear; WIDTH] {
    let diag = &INTERNAL_DIAG;
    let sum: BabyBear = state.iter().copied().fold(BabyBear::ZERO, |a, b| a + b);
    let mut result = [BabyBear::ZERO; WIDTH];
    for i in 0..WIDTH {
        result[i] = sum + (diag[i] - BabyBear::ONE) * state[i];
    }
    result
}

/// Compute one full (external) round of Poseidon2.
pub fn compute_full_round(
    state: &[BabyBear; WIDTH],
    round_constants: &[BabyBear; WIDTH],
) -> [BabyBear; WIDTH] {
    let mut s = [BabyBear::ZERO; WIDTH];
    for i in 0..WIDTH {
        s[i] = Poseidon2State::sbox(state[i] + round_constants[i]);
    }
    apply_external_linear_layer(&s)
}

/// Compute one partial (internal) round of Poseidon2.
pub fn compute_partial_round(
    state: &[BabyBear; WIDTH],
    round_constant: BabyBear,
) -> [BabyBear; WIDTH] {
    let mut s = *state;
    s[0] = Poseidon2State::sbox(s[0] + round_constant);
    apply_internal_linear_layer(&s)
}

/// Compute the expected next state for a given round index (0-indexed).
pub fn compute_round(state: &[BabyBear; WIDTH], round_idx: usize) -> [BabyBear; WIDTH] {
    let rc = &*ROUND_CONSTANTS;
    if round_idx < EXTERNAL_ROUNDS / 2 {
        compute_full_round(state, &rc[round_idx])
    } else if round_idx < EXTERNAL_ROUNDS / 2 + INTERNAL_ROUNDS {
        compute_partial_round(state, rc[round_idx][0])
    } else if round_idx < TOTAL_ROUNDS {
        compute_full_round(state, &rc[round_idx])
    } else {
        *state
    }
}

/// Hash 4 field elements using Poseidon2 (4-to-1 compression).
/// This is used for the 4-ary Merkle tree internal nodes.
///
/// Input: 4 child hashes (each a single field element)
/// Output: 1 parent hash (a single field element)
///
/// # Domain Separation Scheme
///
/// This module uses a consistent domain separation scheme across all hash functions
/// to prevent cross-domain collisions. The Poseidon2 state is partitioned as:
///
/// - **Rate region** (positions 0..3): absorbs input data
/// - **Capacity region** (positions 4..15): domain separation tags and padding
///
/// Domain tags by function:
/// - `hash_4_to_1`: position 4 = arity (4), positions 5..15 = 0
/// - `hash_2_to_1`: position 4 = arity (2), positions 5..15 = 0
/// - `hash_many`:   position 4 = input length, positions 5..15 = 0
/// - `hash_fact`:   positions 0..4 = data, position 5 = 0xFACF marker, position 6 = 1 (leaf flag)
///
/// These tags are non-overlapping: `hash_4_to_1` and `hash_2_to_1` use arity in pos 4,
/// `hash_many` uses length in pos 4 (which can only equal 2 or 4 if the input IS length 2/4,
/// but the rate absorption pattern differs), and `hash_fact` uses positions 5-6 which are
/// always zero in the other functions.
pub fn hash_4_to_1(inputs: &[BabyBear; 4]) -> BabyBear {
    let mut state = Poseidon2State::new();
    // Rate portion: inputs[0..4]
    state.state[0] = inputs[0];
    state.state[1] = inputs[1];
    state.state[2] = inputs[2];
    state.state[3] = inputs[3];
    // Capacity portion: domain separation tag
    state.state[4] = BabyBear::new(4); // arity tag
    // state[5..15] remain zero (capacity)

    state.permute();
    state.state[0]
}

/// Hash 2 field elements using Poseidon2 (2-to-1 compression).
pub fn hash_2_to_1(left: BabyBear, right: BabyBear) -> BabyBear {
    let mut state = Poseidon2State::new();
    state.state[0] = left;
    state.state[1] = right;
    state.state[4] = BabyBear::new(2); // arity tag

    state.permute();
    state.state[0]
}

/// Hash an arbitrary number of field elements (sponge construction).
/// Rate = 4, capacity = 12.
pub fn hash_many(inputs: &[BabyBear]) -> BabyBear {
    let rate = 4;
    let mut state = Poseidon2State::new();
    // Domain separation: encode length in capacity
    state.state[4] = BabyBear::new(inputs.len() as u32);

    // Absorb phase
    for chunk in inputs.chunks(rate) {
        for (i, &elem) in chunk.iter().enumerate() {
            state.state[i] += elem;
        }
        state.permute();
    }

    // Squeeze: return first element
    state.state[0]
}

/// Hash arbitrary bytes into a single BabyBear field element via Poseidon2.
///
/// Packs the input bytes into field elements (4 bytes per element with modular
/// reduction), then hashes through the sponge construction. This is useful for
/// bridging byte-oriented data (like BLAKE3 commitments) into the field-element
/// domain used by the Poseidon2 Merkle tree.
pub fn hash_bytes(data: &[u8]) -> BabyBear {
    let elements = BabyBear::from_bytes_packed(data);
    hash_many(&elements)
}

/// Hash a leaf fact (predicate + up to 4 terms encoded as field elements) into a single digest.
/// Each fact is up to 5 field elements; we hash them using the Poseidon2 permutation with leaf domain sep.
/// Terms beyond the provided slice are treated as zero.
pub fn hash_fact(predicate: BabyBear, terms: &[BabyBear]) -> BabyBear {
    let mut state = Poseidon2State::new();
    state.state[0] = predicate;
    if !terms.is_empty() {
        state.state[1] = terms[0];
    }
    if terms.len() > 1 {
        state.state[2] = terms[1];
    }
    if terms.len() > 2 {
        state.state[3] = terms[2];
    }
    if terms.len() > 3 {
        state.state[4] = terms[3];
    }
    // Leaf domain separation (different from node)
    state.state[5] = BabyBear::new(0xFACF); // "fact" marker
    state.state[6] = BabyBear::ONE; // leaf flag

    state.permute();
    state.state[0]
}

/// The Poseidon2 round function expressed as constraints.
/// This provides the intermediate values needed by the AIR to verify the hash.
///
/// Returns all intermediate states (for witness generation).
pub fn poseidon2_trace(input_state: &[BabyBear; WIDTH]) -> Vec<[BabyBear; WIDTH]> {
    let mut trace = Vec::with_capacity(TOTAL_ROUNDS + 1);
    let mut state = Poseidon2State::from_elements(input_state);

    // Initial linear layer
    state.external_linear_layer();
    trace.push(state.state);

    let rc = &*ROUND_CONSTANTS;

    // First half external rounds
    for round in 0..EXTERNAL_ROUNDS / 2 {
        for i in 0..WIDTH {
            state.state[i] += rc[round][i];
        }
        for i in 0..WIDTH {
            state.state[i] = Poseidon2State::sbox(state.state[i]);
        }
        state.external_linear_layer();
        trace.push(state.state);
    }

    // Internal rounds
    for round in 0..INTERNAL_ROUNDS {
        let rc_idx = EXTERNAL_ROUNDS / 2 + round;
        state.state[0] += rc[rc_idx][0];
        state.state[0] = Poseidon2State::sbox(state.state[0]);
        state.internal_linear_layer();
        trace.push(state.state);
    }

    // Second half external rounds
    for round in 0..EXTERNAL_ROUNDS / 2 {
        let rc_idx = EXTERNAL_ROUNDS / 2 + INTERNAL_ROUNDS + round;
        for i in 0..WIDTH {
            state.state[i] += rc[rc_idx][i];
        }
        for i in 0..WIDTH {
            state.state[i] = Poseidon2State::sbox(state.state[i]);
        }
        state.external_linear_layer();
        trace.push(state.state);
    }

    trace
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn poseidon2_different_inputs_different_outputs() {
        let a = [
            BabyBear::new(1),
            BabyBear::new(2),
            BabyBear::new(3),
            BabyBear::new(4),
        ];
        let b = [
            BabyBear::new(5),
            BabyBear::new(6),
            BabyBear::new(7),
            BabyBear::new(8),
        ];
        assert_ne!(hash_4_to_1(&a), hash_4_to_1(&b));
    }

    #[test]
    fn poseidon2_non_zero_output() {
        let input = [BabyBear::ZERO; 4];
        let h = hash_4_to_1(&input);
        // With round constants, even zero input should produce non-zero output
        assert_ne!(h, BabyBear::ZERO);
    }

    #[test]
    fn hash_many_works() {
        let inputs: Vec<BabyBear> = (1..=10).map(|i| BabyBear::new(i)).collect();
        let h = hash_many(&inputs);
        assert_ne!(h, BabyBear::ZERO);
    }

    #[test]
    fn poseidon2_trace_consistency() {
        let mut input = [BabyBear::ZERO; WIDTH];
        input[0] = BabyBear::new(10);
        input[1] = BabyBear::new(20);
        input[2] = BabyBear::new(30);
        input[3] = BabyBear::new(40);
        let trace = poseidon2_trace(&input);
        // Should have TOTAL_ROUNDS + 1 states
        assert_eq!(trace.len(), TOTAL_ROUNDS + 1);
        // First state is after initial linear layer
        let mut expected_init = Poseidon2State::from_elements(&input);
        expected_init.external_linear_layer();
        assert_eq!(trace[0], expected_init.state);
        // Last state matches direct permutation
        let mut state = Poseidon2State::from_elements(&input);
        state.permute();
        assert_eq!(*trace.last().unwrap(), state.state);
    }

    #[test]
    fn sbox_power_7() {
        // x^7 for x=2: 128
        let x = BabyBear::new(2);
        let y = Poseidon2State::sbox(x);
        assert_eq!(y.0, 128);
    }

    #[test]
    fn hash_bytes_different_inputs() {
        let h1 = hash_bytes(b"foo");
        let h2 = hash_bytes(b"bar");
        assert_ne!(h1, h2);
    }

    #[test]
    fn hash_bytes_32_byte_input() {
        let commitment = [0xAB_u8; 32];
        let h = hash_bytes(&commitment);
        assert_ne!(h, BabyBear::ZERO);
    }

    /// Known-answer test vector for Poseidon2 permutation over BabyBear width-16.
    ///
    /// Input: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    /// This vector is computed from the Plonky3-compatible round constants
    /// (RC_EXT_INIT, RC_INTERNAL, RC_EXT_FINAL) and internal diagonal (INTERNAL_DIAG)
    /// defined in this module. Any change to these parameters will break this test,
    /// which is the intended behavior: it catches accidental parameter drift.
    #[test]
    fn poseidon2_known_answer_vector() {
        // Input: sequential field elements [0..15]
        let mut input = [BabyBear::ZERO; WIDTH];
        for i in 0..WIDTH {
            input[i] = BabyBear::new(i as u32);
        }
        let mut state = Poseidon2State::from_elements(&input);
        state.permute();

        // Expected output (frozen from implementation with Plonky3-sourced parameters)
        let expected: [u32; 16] = [
            1906786279, 1737026427, 1959749225, 700325316, 1638050605, 1021608788, 1726691001,
            1761127344, 1552405120, 417318995, 36799261, 1215172152, 614923223, 1300746575,
            957311597, 304856115,
        ];

        for i in 0..WIDTH {
            assert_eq!(
                state.state[i].0, expected[i],
                "Poseidon2 permutation output mismatch at position {i}: \
                 got {}, expected {}",
                state.state[i].0, expected[i]
            );
        }
    }

    /// Known-answer test for hash_4_to_1 compression function.
    /// This is the core primitive used in the 4-ary Merkle tree.
    #[test]
    fn hash_4_to_1_known_answer() {
        let h = hash_4_to_1(&[
            BabyBear::new(1),
            BabyBear::new(2),
            BabyBear::new(3),
            BabyBear::new(4),
        ]);
        assert_eq!(
            h.0, 1163579196,
            "hash_4_to_1([1,2,3,4]) known-answer mismatch: got {}, expected 1163579196",
            h.0
        );
    }

    /// Cross-implementation known-answer test (conformance KAT).
    ///
    /// This is the *genuine* conformance check, not a frozen self-snapshot: it
    /// runs the SAME input through BOTH dregg's `Poseidon2State::permute` AND
    /// Plonky3's independently-audited `default_babybear_poseidon2_16()`
    /// (`p3-baby-bear` rev 82cfad73 pinned in the workspace Cargo.toml), then
    /// asserts the full 16-element output state is byte-for-byte identical.
    ///
    /// Both implementations use the standard BabyBear Poseidon2 instance:
    ///   - width 16, S-box x^7, R_F = 8 (4 + 4), R_P = 13
    ///   - external round constants BABYBEAR_POSEIDON2_RC_16_EXTERNAL_{INITIAL,FINAL}
    ///   - internal round constants BABYBEAR_POSEIDON2_RC_16_INTERNAL
    ///   - internal diagonal V = [-2, 1, 2, 1/2, 3, 4, -1/2, -3, -4,
    ///                            1/2^8, 1/4, 1/8, 1/2^27, -1/2^8, -1/16, -1/2^27]
    ///
    /// dregg's constants (RC_EXT_INIT / RC_EXT_FINAL / RC_INTERNAL / INTERNAL_DIAG)
    /// are transcribed from these exact Plonky3 tables, so a match establishes real
    /// conformance to the reference. A mismatch would be a critical finding (a
    /// constant/round/matrix divergence in the crypto TCB).
    ///
    /// Note: Plonky3's `permute_mut` applies the initial external linear layer
    /// then the rounds, identical to dregg's `permute`, so the raw permutation is
    /// the correct unit of comparison (no domain-separation padding involved).
    #[test]
    fn poseidon2_plonky3_cross_check_kat() {
        use crate::field::BABYBEAR_P;
        use crate::plonky3_prover::{from_p3, to_p3};
        use p3_baby_bear::default_babybear_poseidon2_16;
        use p3_baby_bear::BabyBear as P3BabyBear;
        use p3_symmetric::Permutation;

        let perm = default_babybear_poseidon2_16();

        // Test vectors covering edge cases + structured + pseudo-random inputs.
        // Each is 16 canonical u32 values (already < BABYBEAR_P).
        let p = BABYBEAR_P;
        let vectors: Vec<[u32; WIDTH]> = vec![
            // all-zeros
            [0; WIDTH],
            // all-ones
            [1; WIDTH],
            // sequential 0..15
            std::array::from_fn(|i| i as u32),
            // sequential 1..16
            std::array::from_fn(|i| (i as u32) + 1),
            // all p-1 (largest canonical value)
            [p - 1; WIDTH],
            // alternating 0 / p-1
            std::array::from_fn(|i| if i % 2 == 0 { 0 } else { p - 1 }),
            // fixed pseudo-random vector (xorshift-derived, seed 0xD2E66, reduced mod p)
            {
                let mut s: u32 = 0xD2E66;
                std::array::from_fn(|_| {
                    s ^= s << 13;
                    s ^= s >> 17;
                    s ^= s << 5;
                    s % p
                })
            },
            // second fixed pseudo-random vector (seed 0x5EED1)
            {
                let mut s: u32 = 0x5EED1;
                std::array::from_fn(|_| {
                    s ^= s << 13;
                    s ^= s >> 17;
                    s ^= s << 5;
                    s % p
                })
            },
            // powers of two (exercises the inverse-power-of-2 diagonal entries)
            std::array::from_fn(|i| 1u32 << (i % 31)),
        ];

        for (vi, raw) in vectors.iter().enumerate() {
            // dregg permutation
            let mut dregg_input = [BabyBear::ZERO; WIDTH];
            for i in 0..WIDTH {
                dregg_input[i] = BabyBear::new(raw[i]);
            }
            let mut dregg_state = Poseidon2State { state: dregg_input };
            dregg_state.permute();

            // Plonky3 reference permutation on the identical input
            let mut p3_input: [P3BabyBear; WIDTH] =
                std::array::from_fn(|i| to_p3(BabyBear::new(raw[i])));
            perm.permute_mut(&mut p3_input);

            // Assert byte-for-byte (canonical-value) equality across all 16 lanes.
            for i in 0..WIDTH {
                let dregg_out = dregg_state.state[i].canonical_val();
                let p3_out = from_p3(p3_input[i]).0;
                assert_eq!(
                    dregg_out, p3_out,
                    "Poseidon2 conformance MISMATCH on vector {vi} at lane {i}: \
                     dregg={dregg_out}, plonky3={p3_out} (input[{i}]={})",
                    raw[i]
                );
            }
        }
    }
}
