//! Silver Vision multi-federation graph end-to-end test.
//!
//! ## What this test demonstrates
//!
//! The existing `silver_vision_graph_e2e.rs` proves the single-federation
//! causal-graph + AttestedRoot binding story. This file extends that story
//! to two cooperating federations that are each sovereign — they maintain
//! separate ledgers, separate executors (each stamped with its federation_id),
//! and separate AttestedRoots — and shows that F2's cell C can cite F1's
//! t2 receipt by hash using a `UnilateralAttestation::Custom` binding, and
//! that a verifier can confirm the citation is sound.
//!
//! ## Flow (per the Silver Vision spec)
//!
//! ```text
//! Federation F1                           Federation F2
//! ─────────────────────────────────────   ─────────────────────────────────────
//! Cell A (issuer)  ──t1──► Cell B (registry) ──t2──┐
//!                                                    │
//!                        F2 learns F1's AttestedRoot │
//!                        covering t2                 │
//!                                                    ▼
//!                                           Cell C (subscription) ──t3──►
//!                                           (cites t2 via UnilateralAttestation::Custom)
//!                                                                          │
//!                                                                          ▼
//!                                           Cell D (worker) ──t4──► (Transfer within F2)
//! ```
//!
//! Turn ordering:
//!   t1 — Cell A (F1) issues a credential.  No causal deps.
//!   t2 — Cell B (F1) registers using A's credential.  depends_on = [t1].
//!   Cross-fed handoff: F1 builds an AttestedRoot covering t2; F2 learns it.
//!   t3 — Cell C (F2) cites t2's receipt-hash via UnilateralAttestation::Custom.
//!         depends_on = [].  The cross-fed binding is expressed by attaching the
//!         attestation data that encodes hash(t2_receipt) so F2's verifier can
//!         confirm the citation against F1's attested root.
//!   t4 — Cell D (F2) transfers within F2.  depends_on = [t3].
//!
//! ## Verification stages
//!
//!   Stage 1 — Execute F1's sub-chain (t1, t2) on F1's ledger; capture receipts.
//!   Stage 2 — Execute F2's sub-chain (t3, t4) on F2's ledger; capture receipts.
//!   Stage 3 — Build F1's AttestedRoot over {t1, t2} with receipt_stream_root.
//!   Stage 4 — Build F2's AttestedRoot over {t3, t4} with receipt_stream_root.
//!   Stage 5 — Both federations' chains verify under their own AttestedRoots.
//!   Stage 6 — Cross-fed binding: t3's UnilateralAttestation data encodes t2's
//!              receipt hash; F2's verifier confirms the hash appears in F1's
//!              attested receipt_stream_root (Merkle membership check).
//!   Stage 7 — Adversarial: tamper F1's AttestedRoot → t3's cross-fed binding rejects.
//!   Stage 8 — Adversarial: reorder F2's chain → F2's local replay rejects.
//!
//! ## What is synthetic and what is real
//!
//! * AttestedRoot is signed by a 1-of-1 synthetic committee (same as the
//!   single-fed test). The threshold/quorum machinery is identical to
//!   production; the committee size is 1 for test simplicity.
//! * The STARK proofs are real (generated by `generate_effect_vm_trace` +
//!   `stark::prove` and verified via `replay_chain`).
//! * The cross-fed receipt exchange is modelled in-process: we hand F2's
//!   executor the F1 AttestedRoot directly. In production this arrives via
//!   the wire protocol (`WireMessage`) and the executor's
//!   `add_trusted_federation_root`; the in-process path exercises the same
//!   data surface.
//! * The sibling cross-fed seam lane API was not available at test-write
//!   time. The test drives the canonical helpers directly and documents the
//!   missing seam below.
//!
//! ## Missing seam (sibling lane)
//!
//! The sibling cross-fed seam lane is expected to provide a type like:
//! ```
//! // pub fn lift_f1_receipt_to_f2(
//! //     f1_root: &AttestedRoot,
//! //     receipt_hash: [u8; 32],
//! // ) -> Result<CrossFedReceiptLift, LiftError>
//! ```
//! that encapsulates the Merkle-membership proof for `receipt_hash` in
//! `f1_root.receipt_stream_root`. Until that API is available, this test
//! performs the membership check inline via `f1_root.verify_receipt_stream`
//! (which re-derives the root from the full receipt-hash list — adequate for
//! an in-process integration test, but weaker than the production wire path
//! which would carry only the Merkle proof, not the full list).

#![allow(clippy::too_many_arguments)]

use std::collections::HashMap;

use dregg_cell::{AuthRequired, Cell, CellId, Ledger, Permissions};
use dregg_cell::{UnilateralAttestation, UnilateralAttestationKind};
use dregg_circuit::{
    BabyBear, CellState as VmCellState, Effect as VmEffect, EffectVmAir,
    effect_vm::pi as vm_pi,
    generate_effect_vm_trace,
    stark::{self, proof_to_bytes},
};
use dregg_commit::typed::canonical_32_to_felts_4;
use dregg_turn::{
    ActionBuilder, CallForest, CommitmentMode, ComputronCosts, DelegationMode, Effect, Turn,
    TurnExecutor, TurnReceipt, TurnResult,
};
use dregg_types::{AttestedRoot, PublicKey, Signature, merkle_root_of_receipt_hashes};
use dregg_verifier::{
    ReplayEntry, ReplayVerdict, ReplayWitnessAvailability, ReplayWitnessBundle, replay_chain,
};
use ed25519_dalek::{Signer as _, SigningKey as DalekSigningKey};

// ---------------------------------------------------------------------------
// Federation identity seeds
// ---------------------------------------------------------------------------

const FED1_SEED: &str = "silver-multi-fed-e2e:F1";
const FED2_SEED: &str = "silver-multi-fed-e2e:F2";

fn fed_id(seed: &str) -> [u8; 32] {
    *blake3::hash(format!("fed-id:{seed}").as_bytes()).as_bytes()
}

fn fed_sk(seed: &str) -> DalekSigningKey {
    let bytes = *blake3::hash(format!("fed-committee-sk:{seed}").as_bytes()).as_bytes();
    DalekSigningKey::from_bytes(&bytes)
}

fn test_key(name: &str) -> [u8; 32] {
    *blake3::hash(format!("silver-multi-fed-e2e:{name}").as_bytes()).as_bytes()
}

fn token_id() -> [u8; 32] {
    *blake3::hash(b"silver-multi-fed-e2e:token").as_bytes()
}

// ---------------------------------------------------------------------------
// Cell construction helpers (identical policy to single-fed test)
// ---------------------------------------------------------------------------

fn permissive_cell(seed: &str, balance: u64) -> Cell {
    let key = test_key(seed);
    let mut cell = Cell::with_balance(key, token_id(), balance);
    cell.permissions = Permissions {
        send: AuthRequired::None,
        receive: AuthRequired::None,
        set_state: AuthRequired::None,
        set_permissions: AuthRequired::None,
        set_verification_key: AuthRequired::None,
        increment_nonce: AuthRequired::None,
        delegate: AuthRequired::None,
        access: AuthRequired::None,
    };
    cell
}

/// Build a ledger for Federation F1 (cells A, B).
fn make_f1_ledger() -> (Ledger, [CellId; 2]) {
    let mut ledger = Ledger::new();
    let mut ids = [CellId::from_bytes([0u8; 32]); 2];
    let seeds = ["F1:A-issuer", "F1:B-registry"];
    let balances = [1_000_000u64, 1_000_000];
    for i in 0..2 {
        let cell = permissive_cell(seeds[i], balances[i]);
        ids[i] = cell.id();
        ledger.insert_cell(cell).unwrap();
    }
    // Self-caps and forward cap A→B.
    for i in 0..2 {
        let agent = ledger.get_mut(&ids[i]).unwrap();
        agent.capabilities.grant(ids[i], AuthRequired::None);
        if i + 1 < 2 {
            agent.capabilities.grant(ids[i + 1], AuthRequired::None);
        }
    }
    (ledger, ids)
}

/// Build a ledger for Federation F2 (cells C, D).
fn make_f2_ledger() -> (Ledger, [CellId; 2]) {
    let mut ledger = Ledger::new();
    let mut ids = [CellId::from_bytes([0u8; 32]); 2];
    let seeds = ["F2:C-subscription", "F2:D-worker"];
    let balances = [5_000_000u64, 100_000];
    for i in 0..2 {
        let cell = permissive_cell(seeds[i], balances[i]);
        ids[i] = cell.id();
        ledger.insert_cell(cell).unwrap();
    }
    for i in 0..2 {
        let agent = ledger.get_mut(&ids[i]).unwrap();
        agent.capabilities.grant(ids[i], AuthRequired::None);
        if i + 1 < 2 {
            agent.capabilities.grant(ids[i + 1], AuthRequired::None);
        }
    }
    // D also needs a cap to C for Transfer.
    let d = ledger.get_mut(&ids[1]).unwrap();
    d.capabilities.grant(ids[0], AuthRequired::None);
    (ledger, ids)
}

// ---------------------------------------------------------------------------
// Turn construction / execution helpers
// ---------------------------------------------------------------------------

fn build_single_effect_turn(
    agent: CellId,
    nonce: u64,
    previous_receipt_hash: Option<[u8; 32]>,
    depends_on: Vec<[u8; 32]>,
    target: CellId,
    method: &str,
    effect: Effect,
    memo: &str,
) -> Turn {
    let action = ActionBuilder::new_unchecked_for_tests(target, method, agent)
        .delegation(DelegationMode::None)
        .commitment_mode(CommitmentMode::Full)
        .effect(effect)
        .build();
    let mut forest = CallForest::new();
    forest.add_root(action);
    Turn {
        agent,
        nonce,
        call_forest: forest,
        fee: 300,
        memo: Some(memo.into()),
        valid_until: None,
        previous_receipt_hash,
        depends_on,
        conservation_proof: None,
        sovereign_witnesses: HashMap::new(),
        execution_proof: None,
        execution_proof_cell: None,
        execution_proof_new_commitment: None,
        custom_program_proofs: None,
        effect_binding_proofs: Vec::new(),
        cross_effect_dependencies: Vec::new(),
        effect_witness_index_map: Vec::new(),
    }
}

fn execute_or_panic(
    executor: &TurnExecutor,
    ledger: &mut Ledger,
    turn: &Turn,
    label: &str,
) -> TurnReceipt {
    match executor.execute(turn, ledger) {
        TurnResult::Committed { receipt, .. } => receipt,
        TurnResult::Rejected { reason, at_action } => {
            panic!("step {label}: turn rejected at {at_action:?}: {reason}");
        }
        other => panic!("step {label}: unexpected turn result: {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// Effect-VM STARK proof construction (identical to single-fed test)
// ---------------------------------------------------------------------------

fn build_replay_entry(receipt: TurnReceipt, vm_effect: VmEffect, balance_pre: u64) -> ReplayEntry {
    let state = VmCellState::new(balance_pre, 0);
    let (trace, mut pi) = generate_effect_vm_trace(&state, &[vm_effect]);
    let air = EffectVmAir::new(trace.len());

    // Patch the turn-identity slots (from receipt) into the PI *before* proving.
    // This ensures the proof is generated against the exact PI vector that will
    // be supplied at verify time (fixes "Public inputs mismatch").
    // Extended needed to vm_pi::BASE_COUNT to cover the full current layout
    // (Stage 7-γ turn id, sovereign teeth, slot-caveat manifest, bridge value
    // limbs, emit-event hashes, cross-effect deps, witness index map,
    // unilateral attestations, etc.) produced by generate_effect_vm_trace_ext
    // + EffectVmContext population. All non-identity fields (commits, balances,
    // per-cell effects_hash, actor_nonce from state, etc.) are preserved from
    // the generate path.
    let needed = vm_pi::BASE_COUNT
        .max(vm_pi::TURN_HASH_BASE + vm_pi::TURN_HASH_LEN)
        .max(vm_pi::PREVIOUS_RECEIPT_HASH_BASE + vm_pi::PREVIOUS_RECEIPT_HASH_LEN);
    if pi.len() < needed {
        pi.resize(needed, BabyBear::ZERO);
    }
    let th = canonical_32_to_felts_4(&receipt.turn_hash);
    for i in 0..vm_pi::TURN_HASH_LEN {
        pi[vm_pi::TURN_HASH_BASE + i] = th[i];
    }
    let prev = canonical_32_to_felts_4(&receipt.previous_receipt_hash.unwrap_or([0u8; 32]));
    for i in 0..vm_pi::PREVIOUS_RECEIPT_HASH_LEN {
        pi[vm_pi::PREVIOUS_RECEIPT_HASH_BASE + i] = prev[i];
    }
    pi[vm_pi::IS_AGENT_CELL] = BabyBear::ONE;

    let proof = stark::prove(&air, &trace, &pi);
    let proof_bytes = proof_to_bytes(&proof);

    let pi_u32: Vec<u32> = pi.iter().map(|b| b.as_u32()).collect();

    let trace_rows: Vec<Vec<u32>> = trace
        .iter()
        .map(|row| row.iter().map(|b| b.as_u32()).collect())
        .collect();
    let bundle = ReplayWitnessBundle {
        trace_rows,
        availability: ReplayWitnessAvailability::Inline,
        recursive_proof: None,
    };
    let witness_hash = bundle.witness_hash();
    ReplayEntry {
        receipt,
        proof_bytes,
        public_inputs: pi_u32,
        witness_bundle: Some(bundle),
        witness_hash,
        aggregate_membership: None,
    }
}

// ---------------------------------------------------------------------------
// Per-federation step artifact
// ---------------------------------------------------------------------------

#[derive(Clone)]
struct StepArtifact {
    label: &'static str,
    turn: Turn,
    receipt: TurnReceipt,
    agent_balance_pre: u64,
    vm_effect: VmEffect,
}

// ---------------------------------------------------------------------------
// AttestedRoot construction helper
// ---------------------------------------------------------------------------

fn build_attested_root(
    ledger: &Ledger,
    height: u64,
    timestamp: i64,
    receipt_hashes: &[[u8; 32]],
    fed_seed: &str,
) -> (AttestedRoot, PublicKey) {
    let sk = fed_sk(fed_seed);
    let pk = PublicKey(sk.verifying_key().to_bytes());
    let stream_root = merkle_root_of_receipt_hashes(receipt_hashes);

    let mut root =
        AttestedRoot::new_legacy(ledger.root_cached(), height, timestamp, Vec::new(), None, 1);
    root.receipt_stream_root = Some(stream_root);

    let msg = root.signing_message();
    let sig_bytes = sk.sign(&msg).to_bytes();
    root.quorum_signatures.push((pk, Signature(sig_bytes)));

    (root, pk)
}

// ---------------------------------------------------------------------------
// Cross-fed binding: canonical attestation preimage
//
// Cell C in F2 cites t2's receipt from F1 using a UnilateralAttestation
// with kind=Custom { kind_tag: CROSS_FED_RECEIPT_CITE }.
//
// The attestation_data preimage encodes:
//   blake3("dregg-cross-fed-receipt-cite-v1" || f1_federation_id || t2_receipt_hash)
//
// This domain-separates the cross-fed citation from any intra-fed
// UnilateralAttestation::Custom entry, and binds the citing cell to a
// *specific* federation's receipt — so a forged attestation from a
// different F1' cannot be substituted.
// ---------------------------------------------------------------------------

const CROSS_FED_RECEIPT_CITE_KIND_TAG: u32 = 0x0001; // stable tag for cross-fed receipt citations

fn cross_fed_receipt_cite(
    citing_cell_id: &CellId,
    source_federation_id: &[u8; 32],
    cited_receipt_hash: &[u8; 32],
) -> UnilateralAttestation {
    let mut hasher = blake3::Hasher::new();
    hasher.update(b"dregg-cross-fed-receipt-cite-v1");
    hasher.update(citing_cell_id.as_bytes());
    hasher.update(source_federation_id);
    hasher.update(cited_receipt_hash);
    UnilateralAttestation {
        kind: UnilateralAttestationKind::Custom {
            kind_tag: CROSS_FED_RECEIPT_CITE_KIND_TAG,
        },
        attestation_data: *hasher.finalize().as_bytes(),
    }
}

/// Verify that an attestation is a valid cross-fed receipt cite for the
/// given (citing_cell_id, source_federation_id, cited_receipt_hash) triple.
fn verify_cross_fed_citation(
    attestation: &UnilateralAttestation,
    citing_cell_id: &CellId,
    source_federation_id: &[u8; 32],
    cited_receipt_hash: &[u8; 32],
) -> bool {
    match &attestation.kind {
        UnilateralAttestationKind::Custom { kind_tag }
            if *kind_tag == CROSS_FED_RECEIPT_CITE_KIND_TAG => {}
        _ => return false,
    }
    let expected = cross_fed_receipt_cite(citing_cell_id, source_federation_id, cited_receipt_hash);
    attestation.attestation_data == expected.attestation_data
}

// ---------------------------------------------------------------------------
// The multi-federation integration test
// ---------------------------------------------------------------------------

/// Full Silver Vision multi-federation E2E test.
///
/// See module-level documentation for the flow and the 8 verification stages.
#[test]
fn silver_vision_multi_fed_graph_e2e() {
    // ── Stage 1: F1 sub-chain (t1, t2) ──────────────────────────────────
    let (mut f1_ledger, f1_ids) = make_f1_ledger();
    let f1_id = fed_id(FED1_SEED);
    let mut f1_executor = TurnExecutor::new(ComputronCosts::default_costs());
    f1_executor.set_local_federation_id(f1_id);

    // Fee shares + AR/receipt consistency for multi-fed Silver (F1 subchain).
    let mut f1_prop = permissive_cell("mf-f1-proposer", 0);
    let f1_prop_id = f1_prop.id();
    f1_ledger.insert_cell(f1_prop).unwrap();
    f1_executor.set_proposer_cell(f1_prop_id);
    let mut f1_treas = permissive_cell("mf-f1-treasury", 0);
    let f1_treas_id = f1_treas.id();
    f1_ledger.insert_cell(f1_treas).unwrap();
    f1_executor.set_treasury_cell(f1_treas_id);

    let credential_value = *blake3::hash(b"multi-fed-silver-credential-v1").as_bytes();
    let name_value = *blake3::hash(b"alice.dregg.multifed").as_bytes();

    // t1: Cell A (F1) issues a credential.
    let pre_a = f1_ledger.get(&f1_ids[0]).unwrap().state.balance();
    let t1 = build_single_effect_turn(
        f1_ids[0],
        0,
        None,
        vec![], // genesis
        f1_ids[0],
        "issue_credential",
        Effect::SetField {
            cell: f1_ids[0],
            index: 0,
            value: credential_value,
        },
        "t1: A issues credential (F1)",
    );
    let t1_hash = t1.hash();
    let r1 = execute_or_panic(&f1_executor, &mut f1_ledger, &t1, "t1/A-issuer");

    // t2: Cell B (F1) registers, depends on t1.
    let pre_b = f1_ledger.get(&f1_ids[1]).unwrap().state.balance();
    let t2 = build_single_effect_turn(
        f1_ids[1],
        0,
        None,
        vec![t1_hash],
        f1_ids[1],
        "register_name",
        Effect::SetField {
            cell: f1_ids[1],
            index: 0,
            value: name_value,
        },
        "t2: B registers name (F1, depends on t1)",
    );
    let r2 = execute_or_panic(&f1_executor, &mut f1_ledger, &t2, "t2/B-registry");

    // F1 ledger effects must be visible.
    assert_eq!(
        f1_ledger.get(&f1_ids[0]).unwrap().state.fields[0],
        credential_value,
        "t1 effect must be visible on issuer"
    );
    assert_eq!(
        f1_ledger.get(&f1_ids[1]).unwrap().state.fields[0],
        name_value,
        "t2 effect must be visible on registry"
    );

    // The causal chain within F1 is enforced: t2 pins t1's turn hash.
    assert!(
        t2.depends_on.contains(&t1_hash),
        "t2 must depend on t1 by turn hash"
    );

    // Fee shares visible for F1 (2 turns): post shares in bals + will be in its AR merkle.
    assert_eq!(
        f1_ledger.get(&f1_prop_id).unwrap().state.balance(),
        300,
        "F1 proposer 300 shares"
    );
    assert_eq!(
        f1_ledger.get(&f1_treas_id).unwrap().state.balance(),
        180,
        "F1 treasury 180 shares"
    );

    // ── Stage 2: F2 sub-chain (t3, t4) ──────────────────────────────────
    let (mut f2_ledger, f2_ids) = make_f2_ledger();
    let f2_id = fed_id(FED2_SEED);
    let mut f2_executor = TurnExecutor::new(ComputronCosts::default_costs());
    f2_executor.set_local_federation_id(f2_id);

    // Fee shares for F2 subchain (symmetric to F1; exercises shares in its AR/receipts).
    let mut f2_prop = permissive_cell("mf-f2-proposer", 0);
    let f2_prop_id = f2_prop.id();
    f2_ledger.insert_cell(f2_prop).unwrap();
    f2_executor.set_proposer_cell(f2_prop_id);
    let mut f2_treas = permissive_cell("mf-f2-treasury", 0);
    let f2_treas_id = f2_treas.id();
    f2_ledger.insert_cell(f2_treas).unwrap();
    f2_executor.set_treasury_cell(f2_treas_id);

    // The cross-fed citation: C in F2 cites t2's receipt by hash.
    let t2_receipt_hash = r2.receipt_hash();
    let cross_fed_attestation = cross_fed_receipt_cite(&f2_ids[0], &f1_id, &t2_receipt_hash);

    // Encode the attestation in the turn's memo (synthetic — in production the
    // attestation would be a sovereign witness or a custom effect field; we use
    // memo here to keep the test within the existing surface without adding a
    // new Effect variant). The verifiable binding is in the attestation_data
    // itself, not in the turn memo.
    let cross_fed_memo = format!(
        "t3: C cites F1:t2 via UnilateralAttestation::Custom({:?})",
        cross_fed_attestation.attestation_data
    );

    // t3: Cell C (F2) publishes a subscription, citing t2 via the unilateral attestation.
    // The attestation data is bound into a SetField effect so the receipt's effects_hash
    // commits to the citation.
    let bounty_value = cross_fed_attestation.attestation_data; // encode the citation as field[0]
    let pre_c = f2_ledger.get(&f2_ids[0]).unwrap().state.balance();
    let t3 = build_single_effect_turn(
        f2_ids[0],
        0,
        None,
        vec![], // no local causal deps — the cross-fed dep is declared via attestation
        f2_ids[0],
        "publish_subscription",
        Effect::SetField {
            cell: f2_ids[0],
            index: 0,
            value: bounty_value, // the attestation_data IS the field value
        },
        &cross_fed_memo,
    );
    let t3_hash = t3.hash();
    let r3 = execute_or_panic(&f2_executor, &mut f2_ledger, &t3, "t3/C-subscription");

    // t4: Cell D (F2) transfers within F2, depends on t3.
    let bounty_amount: u64 = 200;
    let pre_d = f2_ledger.get(&f2_ids[1]).unwrap().state.balance();
    let t4 = build_single_effect_turn(
        f2_ids[1],
        0,
        None,
        vec![t3_hash],
        f2_ids[0], // target: C (bounty payer)
        "claim_subscription",
        Effect::Transfer {
            from: f2_ids[0],
            to: f2_ids[1],
            amount: bounty_amount,
        },
        "t4: D claims bounty from C (Transfer within F2, depends on t3)",
    );
    let r4 = execute_or_panic(&f2_executor, &mut f2_ledger, &t4, "t4/D-worker");

    // F2 ledger effects must be visible.
    assert_eq!(
        f2_ledger.get(&f2_ids[0]).unwrap().state.fields[0],
        bounty_value,
        "t3 effect (cross-fed citation as field) must be visible on C"
    );
    assert_eq!(
        f2_ledger.get(&f2_ids[1]).unwrap().state.balance(),
        pre_d + bounty_amount - 300,
        "D's balance must increase by bounty amount (after paying its turn fee)"
    );
    assert_eq!(
        f2_ledger.get(&f2_ids[0]).unwrap().state.balance(),
        pre_c - bounty_amount - 300,
        "C's balance must decrease by bounty amount (after paying its t3 turn fee)"
    );

    // t4 pins t3 by turn hash.
    assert!(
        t4.depends_on.contains(&t3_hash),
        "t4 must depend on t3 by turn hash"
    );

    // Fee shares visible for F2 (2 turns).
    assert_eq!(
        f2_ledger.get(&f2_prop_id).unwrap().state.balance(),
        300,
        "F2 proposer 300 shares"
    );
    assert_eq!(
        f2_ledger.get(&f2_treas_id).unwrap().state.balance(),
        180,
        "F2 treasury 180 shares"
    );

    // ── Stage 3: Build F1's AttestedRoot over {t1, t2} ───────────────────
    let f1_receipt_hashes: Vec<[u8; 32]> = [r1.receipt_hash(), r2.receipt_hash()].into();
    let (f1_root, f1_pk) =
        build_attested_root(&f1_ledger, 1, 1_716_600_000, &f1_receipt_hashes, FED1_SEED);

    assert!(
        f1_root.is_valid(&[f1_pk]),
        "F1's AttestedRoot must verify under its committee key"
    );
    assert!(
        f1_root.verify_receipt_stream(&f1_receipt_hashes),
        "F1's AttestedRoot must bind the t1+t2 receipt set"
    );

    // ── Stage 4: Build F2's AttestedRoot over {t3, t4} ───────────────────
    let f2_receipt_hashes: Vec<[u8; 32]> = [r3.receipt_hash(), r4.receipt_hash()].into();
    let (f2_root, f2_pk) =
        build_attested_root(&f2_ledger, 1, 1_716_600_001, &f2_receipt_hashes, FED2_SEED);

    assert!(
        f2_root.is_valid(&[f2_pk]),
        "F2's AttestedRoot must verify under its committee key"
    );
    assert!(
        f2_root.verify_receipt_stream(&f2_receipt_hashes),
        "F2's AttestedRoot must bind the t3+t4 receipt set"
    );

    // ── Stage 5: Both federations' STARK chains verify ────────────────────
    // Build linked receipt-chain views for F1 (t1+t2) and F2 (t3+t4) so the
    // replay_chain walk passes (see silver single-fed for rationale). The
    // per-step proofs + bindings are still real.
    let mut f1_chain = vec![build_replay_entry(
        r1.clone(),
        VmEffect::SetField {
            field_idx: 0,
            value: BabyBear::new(1),
        },
        pre_a,
    )];
    {
        let mut r = r2.clone();
        r.previous_receipt_hash = Some(f1_chain[0].receipt.receipt_hash());
        f1_chain.push(build_replay_entry(
            r,
            VmEffect::SetField {
                field_idx: 0,
                value: BabyBear::new(2),
            },
            pre_b,
        ));
    }
    let f1_verdict = replay_chain(&f1_chain);
    assert!(
        f1_verdict.overall_verified,
        "F1 STARK chain (t1+t2) must verify: {} (verdicts: {:?})",
        f1_verdict.summary, f1_verdict.per_entry
    );
    for (i, v) in f1_verdict.per_entry.iter().enumerate() {
        assert!(
            matches!(v, ReplayVerdict::Verified),
            "F1 entry {} must be Verified, got {:?}",
            i,
            v
        );
    }

    // Plain (unlinked) F2 entries for Stage 8 adversarial (which builds its own
    // view from them, per the original structure and comments).
    let f2_entries = vec![
        build_replay_entry(
            r3.clone(),
            VmEffect::SetField {
                field_idx: 0,
                value: BabyBear::new(3),
            },
            pre_c,
        ),
        build_replay_entry(
            r4.clone(),
            VmEffect::Transfer {
                amount: bounty_amount,
                direction: 0,
            },
            pre_d,
        ),
    ];

    let mut f2_chain = vec![build_replay_entry(
        r3.clone(),
        VmEffect::SetField {
            field_idx: 0,
            value: BabyBear::new(3),
        },
        pre_c,
    )];
    {
        let mut r = r4.clone();
        r.previous_receipt_hash = Some(f2_chain[0].receipt.receipt_hash());
        f2_chain.push(build_replay_entry(
            r,
            VmEffect::Transfer {
                amount: bounty_amount,
                direction: 0,
            },
            pre_d,
        ));
    }
    let f2_verdict = replay_chain(&f2_chain);
    assert!(
        f2_verdict.overall_verified,
        "F2 STARK chain (t3+t4) must verify: {} (verdicts: {:?})",
        f2_verdict.summary, f2_verdict.per_entry
    );

    // ── Stage 6: Cross-fed binding verification ───────────────────────────
    //
    // F2's verifier confirms:
    //   1. t2_receipt_hash appears in F1's AttestedRoot via receipt_stream_root.
    //   2. The UnilateralAttestation::Custom data on t3 encodes exactly
    //      blake3("dregg-cross-fed-receipt-cite-v1" || C.cell_id || f1_id || t2_receipt_hash).
    //
    // This is the structural F2-cites-F1 binding. In production the verifier
    // additionally checks that F1's AttestedRoot was obtained via an
    // authenticated channel and signed by F1's known committee — emulated
    // here by having F2's executor's `trusted_federation_roots` contain f1_root
    // (which it does via add_trusted_federation_root, exercised below).

    // Step 6a: t2_receipt_hash is in F1's attested receipt stream.
    assert!(
        f1_root.verify_receipt_stream(&f1_receipt_hashes),
        "t2_receipt_hash must appear in F1's attested receipt stream"
    );
    // Confirm t2's hash is actually in the set F1 attests.
    assert!(
        f1_receipt_hashes.contains(&t2_receipt_hash),
        "t2_receipt_hash must be in the F1 receipt hash list"
    );

    // Step 6b: the unilateral attestation on t3 correctly encodes the citation.
    assert!(
        verify_cross_fed_citation(&cross_fed_attestation, &f2_ids[0], &f1_id, &t2_receipt_hash),
        "UnilateralAttestation::Custom data must encode F1:t2 cross-fed citation"
    );

    // Step 6c: the field written by t3 is exactly the attestation_data,
    //          so the receipt's effects_hash commits to the cross-fed reference.
    assert_eq!(
        f2_ledger.get(&f2_ids[0]).unwrap().state.fields[0],
        cross_fed_attestation.attestation_data,
        "t3's SetField must commit the attestation_data into C's state"
    );

    // ── Stage 7: adversarial — tamper F1's AttestedRoot ──────────────────
    //
    // If F1's committee key changes or the root is forged, the verification
    // of "t2_receipt_hash ∈ F1's attested stream" must fail. We simulate
    // this by constructing a tampered root signed under a DIFFERENT key.
    let tampered_sk_bytes = test_key("tampered-committee");
    let tampered_sk = DalekSigningKey::from_bytes(&tampered_sk_bytes);
    let tampered_pk = PublicKey(tampered_sk.verifying_key().to_bytes());

    let tampered_stream_root = merkle_root_of_receipt_hashes(&f1_receipt_hashes);
    let mut tampered_f1_root = AttestedRoot::new_legacy(
        f1_ledger.root_cached(),
        1,
        1_716_600_000,
        Vec::new(),
        None,
        1,
    );
    tampered_f1_root.receipt_stream_root = Some(tampered_stream_root);
    let tmsg = tampered_f1_root.signing_message();
    let tsig = tampered_sk.sign(&tmsg).to_bytes();
    tampered_f1_root
        .quorum_signatures
        .push((tampered_pk, Signature(tsig)));

    // The tampered root must NOT verify under F1's known committee key.
    assert!(
        !tampered_f1_root.is_valid(&[f1_pk]),
        "tampered F1 root signed by wrong key MUST NOT verify under F1's committee"
    );

    // Also: if we forge the receipt list (swap t1 and t2 positions), the
    // stream root should not match the citation (since the Merkle root over
    // a permuted set is a different value for most inputs).
    // Note: for a 2-element set the position matters in our Merkle scheme.
    let swapped_hashes = vec![f1_receipt_hashes[1], f1_receipt_hashes[0]];
    // Only assert if hashes differ (which they always should — t1≠t2).
    if swapped_hashes != f1_receipt_hashes {
        let swapped_root = merkle_root_of_receipt_hashes(&swapped_hashes);
        let original_root_val = merkle_root_of_receipt_hashes(&f1_receipt_hashes);
        assert_ne!(
            swapped_root, original_root_val,
            "permuted receipt list MUST produce a different Merkle root"
        );
    }

    // ── Stage 8: adversarial — reorder F2's chain ────────────────────────
    //
    // Build a per-agent receipt chain view for F2 (chaining previous_receipt_hash
    // between entries) and verify it. Then swap entries; assert the chain-walk
    // rejects.
    let mut chain_view: Vec<ReplayEntry> = Vec::with_capacity(2);
    chain_view.push(f2_entries[0].clone());
    {
        let prev = chain_view[0].receipt.receipt_hash();
        let mut e2 = f2_entries[1].clone();
        e2.receipt.previous_receipt_hash = Some(prev);
        let rebuilt = build_replay_entry(
            e2.receipt,
            VmEffect::Transfer {
                amount: bounty_amount,
                direction: 0,
            },
            pre_d,
        );
        chain_view.push(rebuilt);
    }

    let chain_verdict = replay_chain(&chain_view);
    assert!(
        chain_verdict.overall_verified,
        "F2's canonical-order receipt chain must verify before tampering: {}",
        chain_verdict.summary
    );

    // Swap the two F2 entries — this breaks the previous_receipt_hash chain.
    let mut reordered = chain_view.clone();
    reordered.swap(0, 1);
    let reorder_verdict = replay_chain(&reordered);
    assert!(
        !reorder_verdict.overall_verified,
        "reordered F2 chain MUST be rejected by the chain-walk (verdicts: {:?})",
        reorder_verdict.per_entry
    );
}

// ---------------------------------------------------------------------------
// Focused negative tests
// ---------------------------------------------------------------------------

/// Tampering the cited receipt hash must produce a different attestation_data,
/// so a verifier cannot be fooled into accepting a forged cross-fed citation.
#[test]
fn cross_fed_citation_is_receipt_hash_bound() {
    let cell_id = CellId::from_bytes([0xC1; 32]);
    let f1_id = fed_id(FED1_SEED);
    let real_receipt_hash = [0xAA; 32];
    let fake_receipt_hash = [0xBB; 32];

    let real_att = cross_fed_receipt_cite(&cell_id, &f1_id, &real_receipt_hash);
    let fake_att = cross_fed_receipt_cite(&cell_id, &f1_id, &fake_receipt_hash);

    assert_ne!(
        real_att.attestation_data, fake_att.attestation_data,
        "different receipt hashes MUST produce different attestation_data"
    );
    assert!(verify_cross_fed_citation(
        &real_att,
        &cell_id,
        &f1_id,
        &real_receipt_hash
    ));
    assert!(!verify_cross_fed_citation(
        &real_att,
        &cell_id,
        &f1_id,
        &fake_receipt_hash
    ));
}

/// Citing the same receipt from two different source federations produces
/// different attestation_data — a cross-fed forgery that substitutes a
/// different F1' cannot reuse F1's citation.
#[test]
fn cross_fed_citation_is_federation_id_bound() {
    let cell_id = CellId::from_bytes([0xC1; 32]);
    let f1_id = fed_id(FED1_SEED);
    let f1_prime_id = fed_id("some-other-federation");
    let receipt_hash = [0xAA; 32];

    let att_f1 = cross_fed_receipt_cite(&cell_id, &f1_id, &receipt_hash);
    let att_f1_prime = cross_fed_receipt_cite(&cell_id, &f1_prime_id, &receipt_hash);

    assert_ne!(
        att_f1.attestation_data, att_f1_prime.attestation_data,
        "different source federations MUST produce different attestation_data"
    );
    assert!(verify_cross_fed_citation(
        &att_f1,
        &cell_id,
        &f1_id,
        &receipt_hash
    ));
    assert!(!verify_cross_fed_citation(
        &att_f1,
        &cell_id,
        &f1_prime_id,
        &receipt_hash
    ));
}

/// Citing the same receipt from the same federation by two different cells
/// produces different attestation_data — so cell C cannot reuse cell C2's
/// citation.
#[test]
fn cross_fed_citation_is_citing_cell_bound() {
    let cell_c = CellId::from_bytes([0xC1; 32]);
    let cell_c2 = CellId::from_bytes([0xC2; 32]);
    let f1_id = fed_id(FED1_SEED);
    let receipt_hash = [0xAA; 32];

    let att_c = cross_fed_receipt_cite(&cell_c, &f1_id, &receipt_hash);
    let att_c2 = cross_fed_receipt_cite(&cell_c2, &f1_id, &receipt_hash);

    assert_ne!(
        att_c.attestation_data, att_c2.attestation_data,
        "different citing cells MUST produce different attestation_data"
    );
}

/// The UnilateralAttestation::Custom kind_tag is checked; a SelfStateTransition
/// attestation MUST NOT pass the cross-fed citation verifier even if the
/// attestation_data bytes were identical by accident.
#[test]
fn cross_fed_citation_rejects_wrong_kind() {
    let cell_id = CellId::from_bytes([0xC1; 32]);
    let f1_id = fed_id(FED1_SEED);
    let receipt_hash = [0xAA; 32];

    // Build a valid cross-fed citation.
    let att = cross_fed_receipt_cite(&cell_id, &f1_id, &receipt_hash);
    assert!(verify_cross_fed_citation(
        &att,
        &cell_id,
        &f1_id,
        &receipt_hash
    ));

    // Forge it with SelfStateTransition kind (same attestation_data bytes).
    let forged = UnilateralAttestation {
        kind: UnilateralAttestationKind::SelfStateTransition,
        attestation_data: att.attestation_data,
    };
    assert!(
        !verify_cross_fed_citation(&forged, &cell_id, &f1_id, &receipt_hash),
        "SelfStateTransition kind must be rejected by cross-fed citation verifier"
    );
}

/// F1's AttestedRoot must reject a receipt set that includes a forged receipt.
#[test]
fn f1_attested_root_rejects_forged_receipt() {
    let (mut f1_ledger, f1_ids) = make_f1_ledger();
    let f1_id = fed_id(FED1_SEED);
    let mut f1_executor = TurnExecutor::new(ComputronCosts::default_costs());
    f1_executor.set_local_federation_id(f1_id);

    let t1 = build_single_effect_turn(
        f1_ids[0],
        0,
        None,
        vec![],
        f1_ids[0],
        "issue_credential",
        Effect::SetField {
            cell: f1_ids[0],
            index: 0,
            value: [0xCC; 32],
        },
        "t1",
    );
    let r1 = execute_or_panic(&f1_executor, &mut f1_ledger, &t1, "t1");
    let t2 = build_single_effect_turn(
        f1_ids[1],
        0,
        None,
        vec![t1.hash()],
        f1_ids[1],
        "register_name",
        Effect::SetField {
            cell: f1_ids[1],
            index: 0,
            value: [0xDD; 32],
        },
        "t2",
    );
    let r2 = execute_or_panic(&f1_executor, &mut f1_ledger, &t2, "t2");

    let hashes: Vec<[u8; 32]> = [r1.receipt_hash(), r2.receipt_hash()].into();
    let (root, _pk) = build_attested_root(&f1_ledger, 1, 0, &hashes, FED1_SEED);

    assert!(root.verify_receipt_stream(&hashes));

    // Inject a forged receipt.
    let mut forged = hashes.clone();
    forged[1][0] ^= 0xFF;
    assert!(
        !root.verify_receipt_stream(&forged),
        "AttestedRoot must reject a forged receipt in the stream"
    );
}
