/-
# Finite POAG1 tables for Relay Repair and Salvage Lock

These declarations enumerate the duplicate-free legal-state closure of each
small game and the complete state x action transition table over that closure.
The web host dispatches these tables; it does not carry a second implementation
of either state machine.
-/
import Dregg2.Games.PathOfAngels.RelayRepair
import Dregg2.Games.PathOfAngels.SalvageLock
import Dregg2.Tactics

namespace Dregg2.Games.PathOfAngels.FiniteTables

open Dregg2.Games.PathOfAngels

/-! ## Generic finite closure -/

def expandStates {State Action : Type} [DecidableEq State]
    (step : State → Action → Option State) (actions : List Action)
    (states : List State) : List State :=
  (states ++ states.flatMap fun state => actions.filterMap (step state)).eraseDups

def stateClosure {State Action : Type} [DecidableEq State]
    (step : State → Action → Option State) (actions : List Action)
    (initial : State) : Nat → List State
  | 0 => [initial]
  | n + 1 => expandStates step actions (stateClosure step actions initial n)

/-! ## Relay Repair -/

def relayActions : List RelayRepair.Action :=
  [.alphaBeta, .alphaGamma, .betaDelta, .gammaDelta, .deltaOmega]

def relayActionId : RelayRepair.Action → String
  | .alphaBeta => "alpha-beta"
  | .alphaGamma => "alpha-gamma"
  | .betaDelta => "beta-delta"
  | .gammaDelta => "gamma-delta"
  | .deltaOmega => "delta-omega"

def relayActionLabel : RelayRepair.Action → String
  | .alphaBeta => "Install Alpha-Beta"
  | .alphaGamma => "Install Alpha-Gamma"
  | .betaDelta => "Install Beta-Delta"
  | .gammaDelta => "Install Gamma-Delta"
  | .deltaOmega => "Install Delta-Omega"

def relayActionFrom : RelayRepair.Action → String
  | .alphaBeta | .alphaGamma => "alpha"
  | .betaDelta => "beta"
  | .gammaDelta => "gamma"
  | .deltaOmega => "delta"

def relayActionTo : RelayRepair.Action → String
  | .alphaBeta => "beta"
  | .alphaGamma => "gamma"
  | .betaDelta | .gammaDelta => "delta"
  | .deltaOmega => "omega"

def relayPanelMask (panel : RelayRepair.Panel) : Nat :=
  (if panel.alphaBeta then 1 else 0) +
  (if panel.alphaGamma then 2 else 0) +
  (if panel.betaDelta then 4 else 0) +
  (if panel.gammaDelta then 8 else 0) +
  (if panel.deltaOmega then 16 else 0)

/-- The panel and the clock are the whole state; spares are a projection of the
panel against the board, so the id does not name them. -/
def relayStateId (state : RelayRepair.State) : String :=
  "relay:" ++ toString (relayPanelMask state.panel) ++ ":" ++ toString state.turns

def relayInstalledActionIds (panel : RelayRepair.Panel) : List String :=
  (relayActions.filter fun action => RelayRepair.installed panel action).map relayActionId

theorem relayActions_length : relayActions.length = 5 := rfl

theorem relayActions_complete (action : RelayRepair.Action) : action ∈ relayActions := by
  cases action <;> simp [relayActions]

/-- No Config-erased twin exists: the closure is generated by the source transition
itself, parameterised only by the semantically relevant argument. -/
theorem relayStep_eq_source (cfg : RelayRepair.Config) (state : RelayRepair.State)
    (action : RelayRepair.Action) :
    RelayRepair.stepB cfg.board state action = RelayRepair.step cfg state action := rfl

def relayStates (board : RelayRepair.Board) : List RelayRepair.State :=
  stateClosure (RelayRepair.stepB board) relayActions RelayRepair.initialState
    RelayRepair.MAX_TURNS

structure RelayTransition where
  state : RelayRepair.State
  action : RelayRepair.Action
  next : Option RelayRepair.State
deriving DecidableEq, Repr

def relayTransitions (board : RelayRepair.Board) : List RelayTransition :=
  (relayStates board).flatMap fun state =>
    relayActions.map fun action =>
      { state, action, next := RelayRepair.stepB board state action }

def relayTableClosedB (board : RelayRepair.Board) : Bool :=
  (relayTransitions board).all fun transition =>
    match transition.next with
    | none => true
    | some next => decide (next ∈ relayStates board)

def relayStatesNodupB (board : RelayRepair.Board) : Bool := (relayStates board).Nodup

def relayStateIdsUniqueB (board : RelayRepair.Board)
    (stateId : RelayRepair.State → String) : Bool :=
  ((relayStates board).map stateId).Nodup

/-- The complete refusal vocabulary.  A reason no run of the emitted FAMILY can ever
provoke would be a badge no client can earn; `relayRefusalReasons_family_live` is
that check, and `relayRefusalReasons_live_per_board` measures which boards provoke
which — they do NOT all provoke all five. -/
def relayRefusalVocabulary : List String :=
  ["solved", "turn-limit", "already-installed", "no-spares", "stranded"]

def relayRefusalReason (board : RelayRepair.Board) (state : RelayRepair.State)
    (action : RelayRepair.Action) : Option String :=
  if RelayRepair.routedB state.panel then some "solved"
  else if RelayRepair.MAX_TURNS ≤ state.turns then some "turn-limit"
  else if RelayRepair.installed state.panel action then some "already-installed"
  else if RelayRepair.sparesLeft board state.panel < RelayRepair.cost board action then
    some "no-spares"
  else if RelayRepair.completableB board state = false then some "stranded"
  else none

def relayRefusalReasonsCompleteB (board : RelayRepair.Board) : Bool :=
  (relayTransitions board).all fun transition =>
    match transition.next, relayRefusalReason board transition.state transition.action with
    | some _, none => true
    | none, some _ => true
    | _, _ => false

/-- Which declared reasons a run against THIS board can actually provoke. -/
def relayLiveRefusalReasons (board : RelayRepair.Board) : List String :=
  relayRefusalVocabulary.filter fun reason =>
    (relayTransitions board).any fun transition =>
      relayRefusalReason board transition.state transition.action == some reason

/-- Every declared reason is provoked by some reachable (state, action) pair OF THE
FAMILY.  ⚠ Not of every board: see `relayRefusalReasons_live_per_board`. -/
def relayRefusalReasonsFamilyLiveB : Bool :=
  relayRefusalVocabulary.all fun reason =>
    (List.finRange 8).any fun i =>
      (relayLiveRefusalReasons (RelayRepair.boardAt i)).contains reason

/-- Conversely, no row invents a reason outside the vocabulary. -/
def relayRefusalReasonsDeclaredB (board : RelayRepair.Board) : Bool :=
  (relayTransitions board).all fun transition =>
    match relayRefusalReason board transition.state transition.action with
    | none => true
    | some reason => relayRefusalVocabulary.contains reason

theorem relayTransitions_length (board : RelayRepair.Board) :
    (relayTransitions board).length = (relayStates board).length * relayActions.length := by
  simp [relayTransitions]

theorem relayTransition_spec (board : RelayRepair.Board) (transition : RelayTransition)
    (h : transition ∈ relayTransitions board) :
    transition.next = RelayRepair.stepB board transition.state transition.action := by
  simp only [relayTransitions, List.mem_flatMap, List.mem_map] at h
  obtain ⟨state, _hstate, action, _haction, rfl⟩ := h
  rfl

/-! ### The WHOLE board family, not one drawn board

⚠ `relayEmittedBoard := RelayRepair.boardAt 2` is GONE, and with it the eight
theorems that held only of it.  It named the board `Emit.relayRunSeed` drew, and
the run seed was published, so pinning that board pinned the answer.  Relay's
instance is now drawn per run from a slot secret (`HiddenInstance.runSeedFor`),
so there is no emitted board — the descriptor carries all eight machines and the
run opening names which one is live.

Relay is a perfect-information puzzle: its player must read the damage report to
play at all, so the instance is DISCLOSED to its own player at run start.  What
changed is that it is disclosed per run rather than printed once for everyone,
which is what kills the memorised line.

Every property below is now quantified over the whole family, which is strictly
stronger than the pinned-board versions it replaces. -/

/-! ⚑ **THE TABLE PINS NO LONGER EVALUATE IN THIS MODULE (2026-08-08).**  This module is
in the `Dregg2.FFI` closure — the crypto archive's build — and a `native_decide` here made
every game-fixture regression a hard failure of every Rust proving target (the
compilation-unit coupling the stale-fixture outage measured).  The STATEMENTS stay here,
each as an evaluation-free `check_* : Bool` definition (a `def` body elaborates without
running), beside the closure and refusal machinery they are about.  The EVALUATION — each
`check_* = true`, pinned by `native_decide` + `#assert_compiled` — lives in
`FiniteTablesFixtures.lean`, rooted in the `PathOfAngelsGuards` library: a plain
`lake build` still runs every pin, and a stale table reds the guard library instead of the
archive.

⚠ The `∀ i : Fin 8` forms are now `(List.finRange 8).all` Bools, which quantify over the
same eight boards — `List.finRange 8` is exactly the inhabitants of `Fin 8`.

Named residue: NONE.  Nothing in this module needs an evaluated table to elaborate; every
declaration below is a closure, a projection or a Bool.

⚑ **BUT A PARAMETERLESS `check_* : Bool` IS A CLOSED TERM, AND A CLOSED TERM IS FORCED AT
MODULE INIT (2026-09-12).**  Moving the `native_decide` out bought the ELABORATION, not the
RUN: `leanc` compiles a parameterless `def x : Bool` into an `_init_` closed-term computation
that `initialize_Dregg2_Dregg2_Games_PathOfAngels_FiniteTables` forces the first time anything
in the module's closure initialises.  Measured on a client signer linked against an archive
that exports `dregg_poa_signal_judge`, whose `install_verified_mldsa_sign_core_real` ran the
full init before argv was read: `dregg_ffi_init` initialises `NetworkJudge` → `Emit` → this
module, and the six SALVAGE checks below (fifteen seeds × a 12-round closure to 260 states
with quadratic `eraseDups`, plus the 90-seed parametric refinement) had not finished after
three minutes at 5 GB — the process never reached `main`.  They therefore carry a `(_ : Unit)` parameter, which
makes them functions rather than closed terms, so nothing is computed until a pin applies `()`.
The eight RELAY checks above are still parameterless and still forced at init; they are cheap
enough to leave, and their cost is the thing to re-measure before adding another.
Rule: a `check_*` in this module whose body walks a state closure takes `(_ : Unit)`. -/

/-- Every board's transition table is closed: no accepted successor leaves the board's own
enumerated state closure. (Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_relayTable_closed : Bool :=
  (List.finRange 8).all fun i => relayTableClosedB (RelayRepair.boardAt i)

/-- Every board's state closure is duplicate-free.
(Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_relayStates_nodup : Bool :=
  (List.finRange 8).all fun i => relayStatesNodupB (RelayRepair.boardAt i)

/-- Every board's rows refuse exactly when a declared reason fires.
(Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_relayRefusalReasons_complete : Bool :=
  (List.finRange 8).all fun i => relayRefusalReasonsCompleteB (RelayRepair.boardAt i)

/-- ⚑ **REFUTED AND RESTATED.**  The claim carried here until 2026-08-05 was that
every one of the five declared reasons is provoked on every one of the eight boards.
It is FALSE, and `native_decide` said so: boards 0 and 6 carry enough spares that no
reachable (state, action) pair can ever refuse with `"no-spares"`.  The vector below
is the measurement, not a restatement of the hope.
`RESTATED` rather than weakened for convenience — the property that matters is that
the emitted vocabulary is exercised by the emitted FAMILY (no reason is a badge no
run can earn) and that no board invents a reason outside it
(`relayRefusalReasons_declared`).  Which reasons a PARTICULAR board can provoke is a
fact about that board's spare budget, and stating it per board is the strongest true
form. (Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_relayRefusalReasons_live_per_board : Bool :=
  decide (((List.finRange 8).map fun i => relayLiveRefusalReasons (RelayRepair.boardAt i)) =
    [ ["solved", "turn-limit", "already-installed", "stranded"]
    , ["solved", "turn-limit", "already-installed", "no-spares", "stranded"]
    , ["solved", "turn-limit", "already-installed", "no-spares", "stranded"]
    , ["solved", "turn-limit", "already-installed", "no-spares", "stranded"]
    , ["solved", "turn-limit", "already-installed", "no-spares", "stranded"]
    , ["solved", "turn-limit", "already-installed", "no-spares", "stranded"]
    , ["solved", "turn-limit", "already-installed", "stranded"]
    , ["solved", "turn-limit", "already-installed", "no-spares", "stranded"] ])

/-- No declared reason is dead across the whole emitted family.
(Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_relayRefusalReasons_family_live : Bool := relayRefusalReasonsFamilyLiveB

/-- No board invents a reason outside the declared vocabulary.
(Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_relayRefusalReasons_declared : Bool :=
  (List.finRange 8).all fun i => relayRefusalReasonsDeclaredB (RelayRepair.boardAt i)

/-- Every board's emitted state ids are unique, so a client can key on them.
(Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_relayStateIds_unique : Bool :=
  (List.finRange 8).all fun i => relayStateIdsUniqueB (RelayRepair.boardAt i) relayStateId

/-- Per-board closure sizes.  They are NOT all equal: the crate and the pricing
change how much of the panel lattice is reachable, so a client cannot be told one
number.  Board 2 is 25, which is the value the deleted `relayStates_count` pinned. -/
def relayStateCounts : List Nat :=
  (List.finRange 8).map fun i => (relayStates (RelayRepair.boardAt i)).length

/-- The eight per-board closure sizes, pinned as a vector.
(Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_relayStateCounts_pinned : Bool :=
  decide (relayStateCounts = [26, 19, 25, 18, 18, 22, 26, 25])

/-- The emitted row count of a board is its state count times the five links; no
separate pin is needed because `relayTransitions_length` proves it for every board. -/
theorem relayTransitions_count (i : Fin 8) :
    (relayTransitions (RelayRepair.boardAt i)).length =
      (relayStates (RelayRepair.boardAt i)).length * 5 := by
  simp [relayTransitions_length, relayActions_length]

#assert_axioms relayActions_length
#assert_axioms relayActions_complete
#assert_axioms relayStep_eq_source
#assert_axioms relayTransitions_length
#assert_axioms relayTransition_spec
#assert_axioms relayTransitions_count

-- The eight relay pins (`#assert_compiled` + `native_decide`) live in
-- `FiniteTablesFixtures.lean`, rooted in `PathOfAngelsGuards` — see the note above.

/-! ## Salvage Lock -/

def salvageActions : List SalvageLock.Action :=
  (List.finRange 6).map SalvageLock.Action.expose

def salvageActionId (action : SalvageLock.Action) : String :=
  "slot-" ++ toString (SalvageLock.actionSlot action).val

def salvageActionLabel (action : SalvageLock.Action) : String :=
  "Expose plate " ++ toString (SalvageLock.actionSlot action).val

def salvageGlyphLabel (glyph : Fin 3) : String :=
  "glyph-" ++ toString glyph.val

def salvageClearedMask (state : SalvageLock.State) : Nat :=
  SalvageLock.allSlots.foldl (fun mask slot =>
    if slot ∈ state.cleared then mask + 2 ^ slot.val else mask) 0

def salvageStateId (state : SalvageLock.State) : String :=
  let exposed := match state.exposed with
    | none => "none"
    | some slot => toString slot.val
  "salvage:" ++ toString (salvageClearedMask state) ++ ":" ++ exposed ++ ":" ++
    toString state.turns

def salvageClearedSlots (state : SalvageLock.State) : List (Fin 6) :=
  SalvageLock.allSlots.filter fun slot => decide (slot ∈ state.cleared)

theorem salvageActions_length : salvageActions.length = 6 := by
  simp [salvageActions]

theorem salvageActions_complete (action : SalvageLock.Action) : action ∈ salvageActions := by
  cases action with
  | expose slot => simp [salvageActions]

/-- Salvage's source transition parameterized only by the semantically relevant
seed; MissionSpec and reward proofs do not influence play. -/
def salvageStep (seed : Fin SalvageLock.SEED_SPACE) (state : SalvageLock.State) :
    SalvageLock.Action → Option SalvageLock.State
  | .expose slot =>
      if SalvageLock.openB state slot then
        match state.exposed with
        | none => some { state with exposed := some slot, turns := state.turns + 1 }
        | some first =>
            let cleared :=
              if SalvageLock.glyphAt seed first = SalvageLock.glyphAt seed slot then
                insert slot (insert first state.cleared)
              else state.cleared
            some { cleared, exposed := none, turns := state.turns + 1 }
      else none

theorem salvageStep_eq_source (cfg : SalvageLock.Config) (state : SalvageLock.State)
    (action : SalvageLock.Action) :
    salvageStep cfg.seed state action = SalvageLock.step cfg state action := by
  cases action <;> rfl

def salvageStates (seed : Fin SalvageLock.SEED_SPACE) : List SalvageLock.State :=
  stateClosure (salvageStep seed) salvageActions SalvageLock.initialState SalvageLock.MAX_TURNS

structure SalvageTransition where
  state : SalvageLock.State
  action : SalvageLock.Action
  next : Option SalvageLock.State
deriving DecidableEq

def salvageTransitions (seed : Fin SalvageLock.SEED_SPACE) : List SalvageTransition :=
  (salvageStates seed).flatMap fun state =>
    salvageActions.map fun action => { state, action, next := salvageStep seed state action }

/-- `states` is bound OUTSIDE the fold: it used to sit inside the lambda, so the
whole twelve-round closure was recomputed once per transition row (984 times).  That
was affordable only because the old board was two arithmetic operations. -/
def salvageTableClosedB (seed : Fin SalvageLock.SEED_SPACE) : Bool :=
  let states := salvageStates seed
  (salvageTransitions seed).all fun transition =>
    match transition.next with
    | none => true
    | some next => decide (next ∈ states)

def salvageStatesNodupB (seed : Fin SalvageLock.SEED_SPACE) : Bool := (salvageStates seed).Nodup

def salvageStateIdsUniqueB (seed : Fin SalvageLock.SEED_SPACE)
    (stateId : SalvageLock.State → String) : Bool :=
  ((salvageStates seed).map stateId).Nodup

def salvageRefusalReason (state : SalvageLock.State) (action : SalvageLock.Action) :
    Option String :=
  let slot := SalvageLock.actionSlot action
  if SalvageLock.solvedB state then some "solved"
  else if SalvageLock.MAX_TURNS ≤ state.turns then some "turn-limit"
  else if slot ∈ state.cleared then some "cleared-slot"
  else if state.exposed = some slot then some "already-exposed"
  else none

def salvageRefusalReasonsCompleteB (seed : Fin SalvageLock.SEED_SPACE) : Bool :=
  (salvageTransitions seed).all fun transition =>
    match transition.next, salvageRefusalReason transition.state transition.action with
    | some _, none => true
    | none, some _ => true
    | _, _ => false

theorem salvageTransitions_length (seed : Fin SalvageLock.SEED_SPACE) :
    (salvageTransitions seed).length = (salvageStates seed).length * salvageActions.length := by
  simp [salvageTransitions]

theorem salvageTransition_spec (seed : Fin SalvageLock.SEED_SPACE) (transition : SalvageTransition)
    (h : transition ∈ salvageTransitions seed) :
    transition.next = salvageStep seed transition.state transition.action := by
  simp only [salvageTransitions, List.mem_flatMap, List.mem_map] at h
  obtain ⟨state, _hstate, action, _haction, rfl⟩ := h
  rfl

/-- One seed per perfect matching: the fifteen with a canonical glyph labelling
(`seed % 6 = 0`).  The glyph names cannot change the closure — `salvageStep` only
ever compares two glyphs for equality — so these fifteen cover the whole seed space
for any question about the machine's SHAPE. -/
def salvagePairingRepresentatives : List (Fin SalvageLock.SEED_SPACE) :=
  (List.finRange SalvageLock.SEED_SPACE).filter fun seed => seed.val % 6 == 0

/-- Every seed's own machine has the same size and the same hygiene.  Kept because
it is what makes the size of a per-seed table uninformative; it is no longer what
the wire carries. (Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_salvage_machine_shape_is_seed_independent (_ : Unit) : Bool :=
  salvagePairingRepresentatives.length == 15 &&
    (salvagePairingRepresentatives.all (fun seed =>
      (salvageStates seed).length == 260 &&
      (salvageTransitions seed).length == 1560 &&
      salvageStatesNodupB seed &&
      salvageTableClosedB seed &&
      salvageStateIdsUniqueB seed salvageStateId &&
      salvageRefusalReasonsCompleteB seed))

/-! ### The PARAMETRIC machine — the rules without the board

⚠ `salvagePinnedSeed` and its six pinned theorems are GONE.  They described the
table of ONE board, and that table stated the board twice over: once in each
action row's `glyph_id`, and once — unavoidably in a tabulated machine — in the
successors, because which second exposure clears is exactly which plates pair.
The `SalvageLock` header said removing `glyph_id` alone would silence a gate
without hiding anything, and it was right.

What is emitted now carries no board at all.  A first exposure is deterministic
and needs no instance.  A second exposure consults ONE bit — did the two plates
carry the same glyph — and the row names BOTH successors, `on_match` and
`on_mismatch`.  The bit comes from the judge, which holds the live run seed; the
client renders the branch it is told and learns exactly one bit per exposure,
which is what a memory game is supposed to cost.

`salvage_parametric_table_is_the_kernel` is the refinement: for EVERY one of the
ninety seeds and every row of the emitted closure, the parametric row instantiated
at the true match bit IS `salvageStep`.  The table is the rules; the bit is the
instance.  (Its evaluation, like every other pin here, lives in
`FiniteTablesFixtures.lean`.) -/

/-- A row of the emitted parametric machine. -/
inductive ParametricRow where
  /-- The rules refuse regardless of the board.  Every one of Salvage's four
  refusal reasons is board-independent, which is why a refusal leaks nothing. -/
  | refuse (reason : String)
  /-- A first exposure: deterministic, no oracle consulted. -/
  | advance (next : SalvageLock.State)
  /-- A second exposure: the judge supplies one bit and the run takes one of these. -/
  | resolve (onMatch onMismatch : SalvageLock.State)
deriving DecidableEq

/-- The row for a (state, action) pair.  It mentions no seed. -/
def salvageParametricRow (state : SalvageLock.State) (action : SalvageLock.Action) :
    ParametricRow :=
  let slot := SalvageLock.actionSlot action
  match salvageRefusalReason state action with
  | some reason => .refuse reason
  | none =>
      match state.exposed with
      | none => .advance { state with exposed := some slot, turns := state.turns + 1 }
      | some first =>
          .resolve
            { cleared := insert slot (insert first state.cleared)
              exposed := none, turns := state.turns + 1 }
            { cleared := state.cleared, exposed := none, turns := state.turns + 1 }

/-- The single bit a judge supplies for a second exposure.  This is the ONLY place
the board enters play. -/
def salvageMatchB (seed : Fin SalvageLock.SEED_SPACE) (state : SalvageLock.State)
    (action : SalvageLock.Action) : Bool :=
  match state.exposed with
  | none => false
  | some first =>
      SalvageLock.glyphAt seed first ==
        SalvageLock.glyphAt seed (SalvageLock.actionSlot action)

/-- Instantiate a parametric row at an oracle bit. -/
def salvageParametricApply (row : ParametricRow) (matched : Bool) : Option SalvageLock.State :=
  match row with
  | .refuse _ => none
  | .advance next => some next
  | .resolve onMatch onMismatch => some (if matched then onMatch else onMismatch)

def salvageParametricSuccessors (state : SalvageLock.State) (action : SalvageLock.Action) :
    List SalvageLock.State :=
  match salvageParametricRow state action with
  | .refuse _ => []
  | .advance next => [next]
  | .resolve onMatch onMismatch => [onMatch, onMismatch]

/-- The closure under BOTH oracle answers.  It is a strict over-approximation of
any single board's reachable set — some answer sequences are consistent with no
board at all — and that is the point: its size and shape say nothing about which
board is live. -/
def salvageParametricClosure : Nat → List SalvageLock.State
  | 0 => [SalvageLock.initialState]
  | n + 1 =>
      let states := salvageParametricClosure n
      (states ++ states.flatMap fun state =>
        salvageActions.flatMap (salvageParametricSuccessors state)).eraseDups

def salvageParametricStates : List SalvageLock.State :=
  salvageParametricClosure SalvageLock.MAX_TURNS

structure ParametricTransition where
  state : SalvageLock.State
  action : SalvageLock.Action
  row : ParametricRow
deriving DecidableEq

def salvageParametricTransitions : List ParametricTransition :=
  salvageParametricStates.flatMap fun state =>
    salvageActions.map fun action =>
      { state, action, row := salvageParametricRow state action }

def salvageParametricClosedB : Bool :=
  let states := salvageParametricStates
  salvageParametricTransitions.all fun transition =>
    (salvageParametricSuccessors transition.state transition.action).all fun next =>
      decide (next ∈ states)

def salvageParametricStatesNodupB : Bool := salvageParametricStates.Nodup

def salvageParametricStateIdsUniqueB : Bool :=
  (salvageParametricStates.map salvageStateId).Nodup

/-- ⚑ **The refinement.**  For every one of the ninety boards and every emitted
row, the parametric row instantiated at that board's match bit is exactly the
kernel transition.  The emitted table is therefore the complete rules and the
oracle bit is the complete instance: nothing else passes between them. -/
def salvageParametricRefinesB (seed : Fin SalvageLock.SEED_SPACE) : Bool :=
  salvageParametricStates.all fun state =>
    salvageActions.all fun action =>
      salvageParametricApply (salvageParametricRow state action)
          (salvageMatchB seed state action) ==
        salvageStep seed state action

/-- ⚑ **The refinement, over every board.**  For all ninety seeds, the parametric row
instantiated at that seed's match bit is exactly `salvageStep`.
(Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_salvage_parametric_table_is_the_kernel (_ : Unit) : Bool :=
  (List.finRange SalvageLock.SEED_SPACE).all salvageParametricRefinesB

/-- The emitted closure is closed, duplicate-free and uniquely identified.  The
counts are here because a client is told them and must be able to refuse a table
of a different size; they are NOT a property of any board.
(Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_salvage_parametric_table_is_well_formed (_ : Unit) : Bool :=
  salvageParametricClosedB && salvageParametricStatesNodupB &&
    salvageParametricStateIdsUniqueB

/-- The emitted parametric closure has exactly 1016 states (632 before the budget
grew from 12 exposures to 18 — the closure carries `turns`, so a bigger budget is a
bigger table).
(Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_salvageParametricStates_count (_ : Unit) : Bool :=
  decide (salvageParametricStates.length = 1016)

/-- The emitted parametric table has exactly 6096 rows (3792 before the budget grew).
(Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_salvageParametricTransitions_count (_ : Unit) : Bool :=
  decide (salvageParametricTransitions.length = 6096)

/-- The parametric closure strictly contains every single board's reachable set:
a client that fetched a 260-state table could ask which board has 260 reachable
states, and this one cannot be asked that.
(Pinned `= true` in `FiniteTablesFixtures`.) -/
def check_parametric_closure_covers_every_board (_ : Unit) : Bool :=
  (List.finRange SalvageLock.SEED_SPACE).all fun seed =>
    (salvageStates seed).all fun state => salvageParametricStates.contains state

#assert_axioms salvageActions_length
#assert_axioms salvageActions_complete
#assert_axioms salvageStep_eq_source
#assert_axioms salvageTransitions_length
#assert_axioms salvageTransition_spec

-- The six salvage pins (`#assert_compiled` + `native_decide`) live in
-- `FiniteTablesFixtures.lean`, rooted in `PathOfAngelsGuards` — see the note above.

end Dregg2.Games.PathOfAngels.FiniteTables
